### ISSUE TITLE
Make `npm start help` an alias for `npm start -- --help`

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#1]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

JavaScript, Node.js. Knowledge about `npm` would be helpful but are not required.
### ❓ The Motivation

We try to integrate very tightly with `npm` and its eco system. Instead of creating our own [CLI](https://en.wikipedia.org/wiki/Command-line_interface) tool, we want to use `npm` directly. At this point we only use the `npm start` script to start the Hoodie Server, in future we might want to have all kind of commands like `npm start setup`, `npm start console`, etc. `npm start help` is a simple way to prepare the basic setup for it.
### :dart: The goal

When running `npm start help`, the output should be the same as `npm start -- --help`. Tests are not required, but of course very much welcomed.
### :clipboard: Step by Step
- [x] claim this issue: @kellyjandrews 
- [x] mentor: @gr2m
- [ ] [Setup the hoodie repository locally](https://github.com/hoodiehq/hoodie#testing) and make sure that all tests pass
- [ ] Implement the feature. `npm start` executes the `hoodie` binary which is [hoodie/bin/start.js](https://github.com/hoodiehq/hoodie/blob/master/bin/start.js) as defined [here](https://github.com/hoodiehq/hoodie/blob/26016aabf8ab17935561264e14d3954dd821e6ba/package.json#L6-L8). The source code of [package-scripts](https://github.com/kentcdodds/p-s) might be helpful to figure out how to read out the part after `npm start ...`
- [ ] Commit with `feat: npm start help`  
  Don’t worry about wording or amount of commits. We will clean up everything before we merge :)
- [ ] Start a Pull Request. Mention `closes hoodiehq/camp#1` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [ ] Done :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by kellyjandrews** [comment]
I'll claim this one.

**Comment by kellyjandrews** [comment]
What it seem like you want here is essentially a clone of the `p-s` module inside the `start.js` script, is that accurate? Do you also want `./bin/start.js` to remain directly accessible as well?

**Comment by gr2m** [comment]
sorry I just realised I never got back to you on your question, I’m so sorry! 

Meanwhile we had more discussions on Hoodie and CLI and we decided to just stick to the standard notation without hoodie-specific magic. So the `npm start -- --help` is good enough for us :) 

There are still some other issues to work on if you’d still like to contribute something? I'm happy to assist, too
