### ISSUE TITLE
allow `new Account(url)` as shortcut for `new Account({url: url})`

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#10]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

JavaScript, Node.js. Although this is code that runs in the browser, it looks like Node.js code and can be tested with node only.
### :dart: The goal

A URL is required to initialise the [Account Client](https://github.com/hoodiehq/hoodie-account-client#constructor). But instead of requiring to pass in an object with a `.url` property, we want to allow to pass in a string as a shortcut, so these two would be equivalent: 
1. new Account({url: 'http://example.com/account/api'})
2. new Account('http://example.com/account/api')
### :clipboard: Step by Step
- [x] **claim this issue**  @thomasjinlo
- [x] **[Setup the hoodie repository locally](https://github.com/hoodiehq/hoodie-account-client#testing)** and make sure that all tests pass
- [x] **Write a test**. You can add it to [hoodie-account-client/test/integration/constructor-test.js](https://github.com/hoodiehq/hoodie-account-client/blob/master/test/integration/constructor-test.js)
- [x] make sure that the test fails. If it does, commit the change with `test: new Account(url)`. If you get stuck, feel free to push your work in progress, don’t worry about commit messages, we can clean up things before we merge your work.
- [x] **Start a Pull Request**: https://github.com/hoodiehq/hoodie-account-client/pull/114
- [x] **Implement the fix** :) Make sure that tests pass again
- [x] **Commit** with `feat: new Account(url)`
- [x] If you like, do the same for `new AccountAdmin(url)`. See [hoodie-account-client/admin/index.js](https://github.com/hoodiehq/hoodie-account-client/blob/master/admin/index.js) and [hoodie-account-client/test/integration/admin-constructor-test.js](https://github.com/hoodiehq/hoodie-account-client/blob/master/test/integration/admin-constructor-test.js). If not we can do a follow up issue for this one
- [x] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by thomasjinlo** [comment]
Me!
