### ISSUE TITLE
Don’t set "hoodie-start" script if "start" script is set to "hoodie" 

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#103]
### 🤔 What you will need to know
Basic knowledge of Node.js and npm. 

### ❓ The Motivation
We improved the setup experience for new Hoodie apps by directly setting the "start" script in your app’s `package.json` file when you installed `hoodie` with `npm install --save hoodie` via https://github.com/hoodiehq/hoodie/pull/592

We also made sure that we don’t override an existing "start" script via https://github.com/hoodiehq/hoodie/pull/642, by setting "hoodie-start".

But if the "start" script is set to `"hoodie"`, then we don’t need to do anything. 

### 🐞 The Bug
If the `"start"` script is set to `"hoodie"`, `npm install --save hoodie` current sets the `"hoodie-start"` script. But it should not do anything if the start script is set to `"hoodie"` or something like `"hoodie --inMemory"`.

### :clipboard: Step by Step
- [x] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it within a day.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] Unless you are a Hoodie Contributors team member,  fork the [hoodiehq/hoodie repository](https://github.com/hoodiehq/hoodie)
- [x] [**Setup the repository locally**](https://github.com/hoodiehq/hoodie/#testing). Ensure the tests pass.
- [x] We don’t currently have tests for the [`"postinstall"` hook](https://github.com/hoodiehq/hoodie/blob/87e5024c34093c60d843549408e5d650671701ea/package.json#L70), so don’t worry about it. Make the necessary change directly in [hoodie/bin/setup.js](https://github.com/hoodiehq/hoodie/blob/87e5024c34093c60d843549408e5d650671701ea/bin/setup.js)
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#103` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by gautamkrishnar** [comment]
I would like to work on this
Invite me to slack. Your invite form is not working on http://hood.ie/chat/

**Comment by LowProfileDog** [comment]
Welcome @gautamkrishnar!

Does that slack form work for you: https://hoodie-slackin-xuhlegfruy.now.sh ?

The issue is all yours :) I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

**Comment by gautamkrishnar** [comment]
Thanks. https://hoodie-slackin-xuhlegfruy.now.sh worked for me. I am now going through hoodie docs.

**Comment by gr2m** [comment]
Hey @gautamkrishnar how are things going? Anything we can help with?

**Comment by gautamkrishnar** [comment]
Sorry for being late. I was a little busy these days. @gr2m can you please explain me what i need to change.
This statement looks a bit confusing to me:
`
If the "start" script is set to "hoodie", npm install --save hoodie current sets the "hoodie-start" script. But it should not do anything if the start script is set to "hoodie" or something like "hoodie --inMemory".
`

**Comment by gr2m** [comment]
no worries, happy to explain. Try this:

```
mkdir test
cd test
npm init -y
npm install --save hoodie
```

when it’s done, you will see that the package.json file in the test folder you created has a line `    "start": "hoodie"`.

now, remove the `"dependencies"` key from your package.json and `rm -rf node_modules`. Leave the `    "start": "hoodie"` line and run `npm install --save hoodie` again. Open `package.json` and now you will see two lines

```
    "start": "hoodie",
    "start-hoodie": "hoodie"
```

This is what this issue is about. If the `"start"` script already exists and it is set to `"hoodie"` or a value that starts with `"hoodie"`, then do not create the `"start-hoodie"` script to avoid duplication.  The code where all this is happening is in [bin/setup.js](https://github.com/hoodiehq/hoodie/blob/master/bin/setup.js)

Does that help?

**Comment by gautamkrishnar** [comment]
Thinks a lot for your explanation. I will try to fix that soon....
