### ISSUE TITLE
💯 Code Coverage for hoodie

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#107]
### 🤔 What you will need to know

JavaScript, Node.js. Knowledge about [npm](https://docs.npmjs.com/) would be helpful but are not required, you’ll figure it out as you go :)
### :dart: The goal

100% code coverage makes sure that every single line of code is covered by tests. And it looks pretty cool once we have all the 💯 for all modules in [Hoodie’s Architecture](https://github.com/hoodiehq/hoodie/tree/master/server#architecture)

The current status is [![Coverage Status](https://coveralls.io/repos/hoodiehq/hoodie/badge.svg?branch=master)](https://coveralls.io/r/hoodiehq/hoodie?branch=master)

<img width="863" alt="image" src="https://cloud.githubusercontent.com/assets/39992/23769439/3e3557e2-04c4-11e7-8bf4-7cbec98ddbfc.png">

### :clipboard: Step by Step

- [x] claim this issue: @sohini-roy
- [x] replace `up for grabs` label with `in progress`
- [x] [Setup the hoodie repository locally](https://github.com/hoodiehq/hoodie#testing) and make sure that all tests pass
- [x] Bring coverage to 100%. Use the following steps
  - run `npm test`
  - run `node_modules/.bin/nyc report --reporter=lcov`
  - open `coverage/lcov-report/index.html`. It will look something like this: ![coverage](https://cloud.githubusercontent.com/assets/39992/15349428/4806f9ac-1c98-11e6-87c8-9452c222f499.gif)
- [x] If you are all 100%, commit with `test: 100% coverage`. If you have blockers commit with `test: coverage` and move on, we can discuss details in the pull request
- [x] Start a Pull Request. Mention `closes hoodiehq/camp#107` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [x] Done :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by sohini-roy** [comment]
Thank you :)

**Comment by sohini-roy** [comment]
My partner Alice has made a pull request. Please review.
