### ISSUE TITLE
Update License in hoodie-account-server-api repository

### ISSUE THREAD

**Issue by agonzalez0515** [hoodiehq/camp#109]
![writespeakcode](https://s3.postimg.org/5m9xwaxlf/writespeakcode.jpg)
### 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 [About First Timers Only](http://www.firsttimersonly.com/).

### 🤔 What you will need to know

[Write/Speak/Code Open Source Hours README for Hoodie!](https://gist.github.com/polinadotio/ea6bba1e5fe6668b94dd99a8063380ad)
Update License

Change 2016 to 2017

### :clipboard: Step by Step

- [x] 🙋 **Claim this issue**: Comment below. Please only claim if you want to start working on it during [the event](https://www.meetup.com/WriteSpeakCode-SFBay/events/237067347/?from=ref). Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository 
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/) 
In a nutshell: be patient and actively kind
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 📝 **Update**
You will be updating: [LICENSE](https://github.com/hoodiehq/hoodie-account-server-api/blob/master/LICENSE)

```diff
@@ -186,7 +186,7 @@
same "printed page" as the copyright notice for easier
identification within third-party archives.

- Copyright 2012-2016 the Hoodie Community and other contributors.
+ Copyright 2012-2017 the Hoodie Community and other contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
```

- [x] 💾 **Commit** your changes.
- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [ ] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
- [ ] 🔬 **Reviewers**: use the squash & commit button, set commit subject to `chore(LICENSE): update year` and commit body to `closes hoodiehq/camp#109`

### 🤔❓ Questions

You can also ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by morrme** [comment]
If for some reason this is not completed during your event, i'm happy to help. I am in another state, so I cannot attend.

**Comment by morrme** [comment]
This one seems like it is already done as well. Am I looking at the wrong files?

**Comment by gr2m** [comment]
The link to the LICENSE file was wrong, I corrected it, thanks!

**Comment by gr2m** [comment]
@morrme please note that these are first-timers only issues, one per person :) They take us quite some effort to prepare, so we want to make sure to have as many newcomers as possible to have a go at them. As you already worked on #115, I’d like to open this up to someone else. Hope that’s okay with you?

**Comment by morrme** [comment]
Well, I don't have a say in the matter, but I was told earlier that this was for a special event and once the event was over, it was open to anyone. In addition, since all of these had the wrong link, I went to the ones that were unresolved , checked/compared files, and also made comments/screenshots to alert the team of the error(s).  So there was more effort involved on my end as well.  I didn't realize these were just set up for that specific purpose; my thought was that this was something you really needed done ASAP so I was just trying to do my part and help.

**Comment by gr2m** [comment]
No worries at all @morrme, it was our mistake with the link. We are working on a tool that helps us creating issues such as this one, and there was a bug :) 

We are continuously adding issues that are ready for taking, and only the one with the `first-timers-only` label are reserved for people who never contributed to Open Source before. It’s our contribution to http://www.firsttimersonly.com/

**Comment by e-goz** [comment]
Is the event still open ? If so, I'll be pleased to contribute to this issue !

**Comment by gdepouilly** [comment]
Is the event still open ? If so, I'll be pleased to contribute to this issue !

**Comment by LowProfileDog** [comment]
The issue is all yours :) I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

**Comment by gdepouilly** [comment]
I've committed the updates on gh-pages branch, but I can't create the pull request. Which branches should I compare to create it ?

**Comment by gr2m** [comment]
oops, you actually should not be able to commit directly to `gh-pages`, but it’s all good and the issue is now done via https://github.com/hoodiehq/camp/commit/21f7710b971fe94a84a6a2cda1470266e4badfbc :) Thanks!
