### ISSUE TITLE
admin.sessions.add({username}) fails with Not Found

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#11]
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### 🤔 What you will need to know

JavaScript, Node.js. Although this is code that runs in the browser, it looks like Node.js code and can be tested with node only.
### 🐞 The Bug
1. Setup https://github.com/hoodiehq/hoodie-app-tracker
   
   ```
   git clone https://github.com/hoodiehq/hoodie-app-tracker.git
   cd hoodie-app-tracker
   npm install
   npm start
   ```
2. Open http://localhost:8080/hoodie/admin. Sign in with `"secret"` unless you’ve setup an admin password (don’t worry if not).
3. Ceate a user account by running this code in your console
   
   ``` js
   hoodieAdmin.accounts.add({username: 'foo', password: 'bar'})
   ```
   
   Reload the page, it should now appear at `/hoodie/admin`
4. Now Paste this code in the browser console, watch your network tab in developer tools
   
   ``` js
   hoodieAdmin.sessions.add({username: 'foo'})
   ```

See the Network requests as *.har file at https://gist.githubusercontent.com/gr2m/cad2dc6c39cbdd4098b753ab15e54510/raw/ecd9c801529c475e186a631b90ea2311424ba6b3/camp-issue-11-requests.har. You can downdload it and then upload to https://ericduran.github.io/chromeHAR/ for a webviewer. 

### :dart: The goal

When signed in as admin (`hoodieAdmin.isSignedIn()` returns `true`), `hoodieAdmin.sessions.add({username: 'foo'})` should create a user session as documented in https://github.com/hoodiehq/hoodie-account-client/tree/master/admin#adminsessionsadd. 

### :clipboard: Step by Step

- [x] 🙋 **Claim this issue**: Comment below
  Please only claim if you want to start working on it during [the event](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/).
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind
- [x] **[Setup the hoodie repository locally](https://github.com/hoodiehq/hoodie-account-client#testing)** and make sure that all tests pass
- [x] **Write a test**. You can add it to [hoodie-account-client/test/integration/admin-sessions-test.js](https://github.com/hoodiehq/hoodie-account-client/blob/master/test/integration/admin-sessions-test.js).
- [x] make sure that the test fails. If it does, commit the change with `test: admin.sessions.add({username}) fails with "Not Found"`. If you get stuck, feel free to push your work in progress, don’t worry about commit messages, we can clean up things before we merge your work.
- [x] **Start a Pull Request**. Mention `closes hoodiehq/camp#11` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [ ] **Implement the fix** :) Make sure that tests pass again
- [ ] **Commit** with `fix: admin.sessions.add({username}) fails with "Not Found"`
- [ ] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

For a bonus, check out all the other methods that require the admin to be signed in. I think e.g. `admin.accounts.findAll()` are affected, too.

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by barretodaniel** [comment]
Hi there, I'd like to give this a shot.

**Comment by gr2m** [comment]
All yours @barretodaniel :)

**Comment by gr2m** [comment]
How is it going @barretodaniel? Anything we can help with?

**Comment by barretodaniel** [comment]
Hey Gregor, I actually have a couple questions regarding testing but I'm
away from my computer. Until what time are you available today?

**Comment by gr2m** [comment]
I’m in LA timezone, working on Hoodie until 6pm-ish today, so another 5-6h. You can ping me on the [Hoodie Chat](http://hood.ie/chat/), too

**Comment by gr2m** [comment]
Hey @barretodaniel I’ll open this issue up for others to work on, but happy to help you find something else in future if you are interested. Just ping me in the [Hoodie Chat](http://hood.ie/chat/)

**Comment by barretodaniel** [comment]
No problem. Things got really complicated with school. I will let you know
when I can get back into contributing.

Thanks for all the help so far.

**Comment by matthewlanders** [comment]
hey @gr2m! Do you mind if I take this?

**Comment by gr2m** [comment]
not at all! I’ve invited you to this repository, you can accept the invitation here: https://github.com/hoodiehq/camp/invitations

once accepted, please assign yourself and work off the checkboxes above :) Let us know if you need any help or have any questions. Enjoy!

**Comment by matthewlanders** [comment]
Hey @gr2m! I have pushed a couple of commits. The first is the failing test, and the second is my solution (so far).

I was going through the code and thought that might be a good place to call the `admin.sessions.add` function: https://github.com/mmlanders23/hoodie-account-client/commit/cb990381fa8be51dc290d518ba4e8b85ab0c206a

I reasoned that this might be an appropriate place because the admin is signing in, and the conditional qualifies that the user is, in fact, an admin.

My code is breaking a lot of the tests and I am finding it difficult to debug. If you have some time, I would really appreciate some guidance; whether it be general or specific things I am doing wrong/should consider.

**Comment by gr2m** [comment]
Hey @mmlanders23 I fear you got a little lost in the code. The place that implements `admin.sessions.add` is here: [/admin/lib/sessions/add.js](https://github.com/hoodiehq/hoodie-account-client/blob/8ce3b89491cb4ccdb1a698508d2fac6d65804ca4/admin/lib/sessions/add.js)

I know it’s a bit confusing: `hoodie-account-client` basically implements two clients

1. Client for normal users
2. Client for admins

This issue is about the latter. See [/admin](https://github.com/hoodiehq/hoodie-account-client/tree/8ce3b89491cb4ccdb1a698508d2fac6d65804ca4/admin) for more information on it

**Comment by matthewlanders** [comment]
Hey @gr2m, thanks for the response! Ah, I see. Upon reviewing the info, and re-reading the description of the issues above, I think I might have misunderstood the bug.

To clarify the issue, the bug is that when I am signed in as an admin, I should be able to create sessions for another user.

The bug is NOT that sessions are not being created for admins upon sign-in.

Is that correct?

**Comment by gr2m** [comment]
correct 👍

**Comment by matthewlanders** [comment]
Hey @gr2m, sorry for the delay here, holiday traveling made it difficult to work on this.

I am trying to identify the source of the issue. Maybe you can help clarify my understanding of the primary code at work here: hoodie-account-client/admin/lib/sessions/add.js

This is my understanding:

- We look for the user with the accountsFindAll method and we assign the response to the variable accountInfo
- Then we make a post request to create the session for that user
- We hit the proper sessions endpoint with the user's id (which we have stored from the result of the accountsFindAll call)
- We include the admin's session id in the header of the post request to ensure proper authorization

Also, I made another commit with the test re-written to reflect my clarified understanding on the bug. It's expectedly failing but any feedback you could offer there would be awesome!

As always, your guidance is very much appreciated.

**Comment by gr2m** [comment]
Yes that is all correct.

I just had a look myself since the issue is quite old now and we had lots of updates. I think the client is actually doing the right thing, it’s possible that it was fixed by someone else while working on the account client.

But it turns out that the server does not even define a route to create sessions for a user. The specification is here: http://docs.accountjsonapi.apiary.io/#reference/admins/user-session/create. There should be a `POST /accounts/{id}/session` route defined in [hoodie-account-server/routes/accounts.js](https://github.com/hoodiehq/hoodie-account-server/blob/64894ceecebb6af5e1bb1021164a254a789fbf1a/routes/accounts.js), but there is none. This is now the reason for the 404.

Do you want to look into that? 

I’ll have a look at your PR, it still makes sense to add a test for this request 👍

**Comment by gr2m** [comment]
@mmlanders23 are you still interested to work on this?
