### ISSUE TITLE
Update License Year in hoodie-store-server repository

### ISSUE THREAD

**Issue by Techforchange** [hoodiehq/camp#110]
![writespeakcode](https://s3.postimg.org/5m9xwaxlf/writespeakcode.jpg)
### 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 [About First Timers Only](http://www.firsttimersonly.com/).

### 🤔 What you will need to know

[Write/Speak/Code Open Source Hours README for Hoodie!](https://gist.github.com/polinadotio/ea6bba1e5fe6668b94dd99a8063380ad)
Update LICENSE

Changes the year 2016 to 2017

### :clipboard: Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. Please only claim if you want to start working on it during [the event](https://www.meetup.com/WriteSpeakCode-SFBay/events/237067347/?from=ref). Once claimed we add you as contributor to this repository.
- [ ] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository 
- [ ] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/) 
In a nutshell: be patient and actively kind
- [ ] 🔄 **replace** the `up for grabs` label with `in progress`.
- [ ] 📝 **Update**
You will be updating: [LICENSE](https://github.com/hoodiehq/hoodie-store-server/blob/4dc3662a0a685f609e9b35fc11648a71aee5992b/LICENSE)

```diff
@@ -186,7 +186,7 @@
same "printed page" as the copyright notice for easier
identification within third-party archives.

- Copyright 2012-2016 the Hoodie Community and other contributors.
+ Copyright 2012-2017 the Hoodie Community and other contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
```

- [ ] 💾 **Commit** your changes.
- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [ ] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
- [ ] 🔬 **Reviewers**: use the squash & commit button, set commit subject to `chore(LICENSE): update year` and commit body to `closes hoodiehq/camp#110`
### 🤔❓ Questions

You can also ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by amyngyn** [comment]
Claiming this!

**Comment by amyngyn** [comment]
Please review me!
