### ISSUE TITLE
Update License Year in pouchdb-hoodie-api repository

### ISSUE THREAD

**Issue by Techforchange** [hoodiehq/camp#115]
![writespeakcode](https://s3.postimg.org/5m9xwaxlf/writespeakcode.jpg)
### 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 [About First Timers Only](http://www.firsttimersonly.com/).

### 🤔 What you will need to know

[Write/Speak/Code Open Source Hours README for Hoodie!](https://gist.github.com/polinadotio/ea6bba1e5fe6668b94dd99a8063380ad)
Update LICENSE

Changes the year 2016 to 2017

### :clipboard: Step by Step

- [x] 🙋 **Claim this issue**: Comment below. Please only claim if you want to start working on it during [the event](https://www.meetup.com/WriteSpeakCode-SFBay/events/237067347/?from=ref). Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository 
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/) 
In a nutshell: be patient and actively kind
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 📝 **Update**
You will be updating: [LICENSE](https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/LICENSE)

```diff
@@ -186,7 +186,7 @@
same "printed page" as the copyright notice for easier
identification within third-party archives.

- Copyright 2012-2016 the Hoodie Community and other contributors.
+ Copyright 2012-2017 the Hoodie Community and other contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
```

- [x] 💾 **Commit** your changes.
- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
- [x] 🔬 **Reviewers**: use the squash & commit button, set commit subject to `chore(LICENSE): update year` and commit body to `closes hoodiehq/camp#115`
### 🤔❓ Questions

You can also ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by morrme** [comment]
@gr2m @Techforchange I'd like to claim this one, now that the event has passed.

**Comment by LowProfileDog** [comment]
The issue is all yours :) I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

**Comment by morrme** [comment]
@LowProfileDog it looks like this one was already completed by @Techforchange  . The year is already 2017.

**Comment by evilzero** [comment]
File updated with browser

**Comment by morrme** [comment]
@evilzero  ???

**Comment by morrme** [comment]
This is how the license appears in the repo currently. It appears as though the change has already been made. 
![pouchdblic](https://cloud.githubusercontent.com/assets/26514778/24318571/85481850-10d5-11e7-9006-09d5549e3c93.PNG)

**Comment by gr2m** [comment]
The `LICENSE` link in the issue description was wrong, it was linked to a branch in which the file was in fact already corrected, but this was just internal for testing. It is not yet done in the master branch: https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/LICENSE#L189

Could you send a pull request for it?

**Comment by morrme** [comment]
@gr2m i sure will. thanks !

**Comment by morrme** [comment]
@gr2m done! Thanks!
