### ISSUE TITLE
admin.signOut() throws "TypeError: Cannot read property 'session' of null"

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#12]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

JavaScript, Node.js. Although this is code that runs in the browser, it looks like Node.js code and can be tested with node only.
### 🐞 The Bug
1. Setup https://github.com/hoodiehq/hoodie-app-tracker
   
   ```
   git clone https://github.com/hoodiehq/hoodie-app-tracker.git
   cd hoodie-app-tracker
   npm install
   npm start
   ```
2. Open http://localhost:8080/hoodie/admin.
3. Run this code in your console
   
   ``` js
   hoodieAdmin.signOut()
   ```
### :dart: The goal

When not signed in, `hoodieAdmin.signOut()` should reject with `UnauthenticatedError: Not signed in`
### :clipboard: Step by Step
- [x] **claim this issue**  @capellini
- [x] **[Setup the hoodie repository locally](https://github.com/hoodiehq/hoodie-account-client#testing)** and make sure that all tests pass
- [x] **Update the docs** at [hoodie-account-client/admin/README.md](https://github.com/hoodiehq/hoodie-account-client/blob/master/admin/README.md). Add `UnauthenticatedError: Not signed in` to the ["rejects with"](https://github.com/hoodiehq/hoodie-account-client/blob/master/admin/README.md#adminsignout) table
- [x] **Write a test**. You can add it to [hoodie-account-client/test/unit/sign-out-test.js](https://github.com/hoodiehq/hoodie-account-client/blob/master/test/unit/sign-out-test.js). You can also add a new file for sign out to [hoodie-account-client/test/integration](https://github.com/hoodiehq/hoodie-account-client/tree/master/test/integration)
- [x] make sure that the test fails. If it does, commit the change with `test: admin.signOut() throws error when signed out`. If you get stuck, feel free to push your work in progress, don’t worry about commit messages, we can clean up things before we merge your work.
- [x] **Start a Pull Request** https://github.com/hoodiehq/hoodie-account-client/pull/113
- [x] **Implement the fix** :) Make sure that tests pass again
- [x] **Commit** with `fix: admin.signOut() throws error when signed out`
- [x] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by capellini** [comment]
I'll claim this.

**Comment by gr2m** [comment]
All yours 👍 Please let us know if you have any questions

**Comment by capellini** [comment]
Code is ready for review (with a few comments on the integration test that I created).  Thanks for the opportunity to contribute to such a great project!  I'm looking forward to your comments and to contributing more in the future.

**Comment by gr2m** [comment]
Welcome to Hoodie @capellini 🐶 💐 I've invited you to the Hoodie contributors team on GitHub :)

We like giving shout outs to our new contributors on Twitter, do you have a twitter account? Of course nevermind us if you prefer us not to :)

**Comment by capellini** [comment]
Happy to be a member of the contributors team!  Sure, a shout out would be wonderful.  My twitter handle is @capellini.
