### ISSUE TITLE
`signin` is not fired when logging in via token

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#120]
### 🐞 The Bug

Hoodie allows to sign in with a one-time token which must have been added to the user account on the server before, like so

```js
account.signIn({
  username: username,
  token: 'MY_SECRET_TOKEN'
})
```

But as described in https://github.com/hoodiehq/hoodie-account-client/issues/144, the `'signin'` event is not triggered, instead `'reauthenticate'` is triggered.

To reproduce the bug, create a new Hoodie app as described in our [quick start guide](http://docs.hood.ie/en/latest/guides/quickstart.html). As this is just for debugging purpose, I would recommend to start the app in memory by default, for that you can add 

```json
  "hoodie": {
    "inMemory": true
  }
```

to the created package.json file.

Next, let’s create a test account each time we start the app and add a token to it. For that, create an [app-specific plugin](http://docs.hood.ie/en/latest/guides/plugins.html#app-specific-plugins). Create a `hoodie/server.js` file with the following content

```js
module.exports = function (server, options, next) {
  var api = server.plugins.account.api

  api.accounts.add({
    username: 'test',
    password: 'test'
  })

  .then(function (account) {
    console.log('test account created')

    return api.account(account.id).tokens.add({
      id: 'MY_SECRET_TOKEN',
      type: 'login',
      timeout: 7200 // 2h
    })
  })

  .then(function (token) {
    console.log('token added to test account: ' + token.id)
    next()
  })

  .catch(function (error) {
    console.log(error)
    next()
  })
}

module.exports.attributes = {
  name: 'test'
}
```

Now when you start the app, you should see the following in the terminal

```bash
test account created
token added to test account: MY_SECRET_TOKEN
```

Now open [http://localhost:8080](http://localhost:8080) in your browser, open the console in the web developer tools and run this

```js
hoodie.account.on('signin', function () {console.log('signin event')})
hoodie.account.on('reauthenticate', function () {console.log('reauthenticate event')})
hoodie.account.signIn({token: 'MY_SECRET_TOKEN'})
```

You should now see `reauthenticate event` being logged. And that is the bug, because it should have logged `signin event` instead.

Now, git clone the [hoodie-account-client](https://github.com/hoodiehq/hoodie-account-client) repository in a different folder and install its dependencies

```
cd ~ # change directory to somewhere outside of the hoodie app you created before
git clone git@github.com:hoodiehq/hoodie-account-client.git
cd hoodie-account-client
npm install
```

Then copy the current path, on Mac/Linux you can do that with the `pwd` command

Then change again into the directory of your app and run `npm link /path/to/hoodie-account/client` (where `/path/to/hoodie-account/client` is the path you copied above). Now when you restart your test app, it will bundle your local hoodie-account-client copy, so you can make changes and see if it fixes the problem.

That’s basically it :slightly_smiling_face:

### :clipboard: Step by Step

- [x] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it within a day.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] reproduce the bug as described above
- [x] create a test in the `hoodie-account-client` repository which reproduces the problem.
- [x] fix the problem so that the tests pass. Make sure it also works with your local test app now
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#123` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by Alice-anjali** [comment]
We will start right away :-)

**Comment by sohini-roy** [comment]
![screenshot from 2017-06-20 21-04-08](https://user-images.githubusercontent.com/16969415/27341874-2adeeb8e-55fc-11e7-93d7-197923eafb0c.png)

**Comment by sohini-roy** [comment]
I must have missed something for running "hoodie.account.signIn({token: 'MY_SECRET_TOKEN'})" shows "signin event" :sweat_smile:

**Comment by sohini-roy** [comment]
resolved in https://github.com/hoodiehq/hoodie-account-client/pull/157 please review :)
