### ISSUE TITLE
Joining you

### ISSUE THREAD

**Issue by EladKeyshawn** [hoodiehq/camp#124]
Hi I'm Elad and I found your project really interesting and i'd love to contribute. currently I haven't seen some really small task I could contribute. So it'd be nice if you could point me out!
P.S
I'd love to join you organization so I could view all of you cool projects. 
Thanks! 😄

**Comment by gr2m** [comment]
Welcome Elad! We  currently don’t have open issues for small tasks, but I'm sure we will find some soon! You can watch this repository to be nodified
