### ISSUE TITLE
Documentation: add "name" option

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#125]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).

### 🆕🐥☝ First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 [About First Timers Only](http://www.firsttimersonly.com/).

### 🤔 What you will need to know

No coding or git skills are required to work on this issue. You can edit the [Configuration Guide source file](https://github.com/hoodiehq/hoodie/blob/84dc5c1ad985d1b61cf713b2313501c0285312de/docs/guides/configuration.rst) directly on github.com, you don’t even need to install anything on your computer – unless you want to, of course :)

Here is the current version of the Configuration Guide: http://docs.hood.ie/en/latest/guides/configuration.html

In the [Options table](http://docs.hood.ie/en/latest/guides/configuration.html#options) there is an option missing: `name`. Its default value is the application’s package.json’s `"name"` value.

The `name` option is used in the application’s admin dashboard and in the route prefix of [app-specific plugins](http://docs.hood.ie/en/latest/guides/plugins.html#app-specific-plugins). 

### :clipboard: Step by Step
- [ ] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it within a day.  
  Once claimed we add you as contributor to this repository.
- [ ] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [ ] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [ ] 🔄 **replace** the `up for grabs` label with `in progress`.
- [ ] Click the 🖊 icon on the top right of the [configuration.rst file](https://github.com/hoodiehq/hoodie/blob/master/docs/guides/configuration.rst)
- [ ] Add a new row for the `name` option between `inMemory` and `port` (they are alphabetically sorted)
- [ ] Scroll to the bottom of the page and set the text input below `Commit changes` to `docs(configuration guid): add "name" option`. Click the green "Propose file change" button
- [ ] On the next page Click the green "Create pull request" button. Congratulations, you just created a pull request ✨ 
- [ ] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by gr2m** [comment]
@aylincakal is working on it at https://github.com/hoodiehq/hoodie/pull/796

**Comment by usmandap** [comment]
@gr2m Hey let me know if anyhow she is not working. May be I can contribute.

**Comment by gr2m** [comment]
@usmandap Aylin asked me to open up the issue for other people, so if you are still interested, the issue is all yours :) I’ve invited you as collaborator to this repository so you can check of the checkboxes above 👍

**Comment by ojasbansal** [comment]
@gr2m Hey I'm a newbie. Can i contribute ?
 I had never contribute to open source. how can i start?

**Comment by ojas1234** [comment]
@gr2m I had never contribute to open source. how can i start?

**Comment by harshil1712** [comment]
Hello. I would like to contribute. I am a newbie. Please let me know how can I contribute.

**Comment by gr2m** [comment]
The issue has been resolved via https://github.com/hoodiehq/hoodie/commit/f14cd935f8f2e8ae9e4ff213af380d807aedb4d6.

I’m sorry we don’t have open issues right now that we could use to onboard more contributors. I’ll let you know once we have some. You can also watch this repository :)
