### ISSUE TITLE
Upgrade hoodie-app-mapchat to new Hoodie

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#14]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### :dart: The goal

The [MapChat App](https://github.com/hoodiehq/hoodie-app-mapchat) is an example application we built quite a while a go for the old Hoodie. As our Camp Release is about to come out we would like to update it to the latest hoodie. We also use it for a tutorial and would like to update it for the new release, see http://docs.hood.ie/camp/tutorials/map-app.html
### :clipboard: Step by Step
- [x] **claim this issue**: @machikoyasuda 
- [ ] **Migrate all the usage of Hoodie to the new API** :) We recently migrated [hoodie-app-skeleton](https://github.com/hoodiehq/hoodie-app-skeleton), see the diff here: https://github.com/hoodiehq/hoodie-app-skeleton/compare/master...camp. You can compare the old [hoodie.store API](http://docs.hood.ie/en/techdocs/api/client/hoodie.store.html) to the [new one](http://docs.hood.ie/camp/techdocs/api/client/hoodie.store.html), and the [old hoodie.account API](http://docs.hood.ie/en/techdocs/api/client/hoodie.account.html) to the [new one](http://docs.hood.ie/camp/techdocs/api/client/hoodie.account.html)
- [ ] **Commit** anyway you like :) We can clean up before merging. I’d suggest you commit something as soon as you get started.
- [ ] **Start a Pull Request**. Mention `closes hoodiehq/camp#10` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [ ] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by machikoyasuda** [comment]
I would like to claim this issue!

**Comment by gr2m** [comment]
All yours :)

**Comment by machikoyasuda** [comment]
Starting it here with our open source pair programming meetup group in LA: https://github.com/fullstackla/hoodie-map-chat-demo 

Added a bunch of LA locations in our test app for @gr2m :)

![screenshot 2016-07-15 12 18 43](https://cloud.githubusercontent.com/assets/3673236/16885986/4fcb9942-4a86-11e6-8082-4750ac251838.png)

**Comment by machikoyasuda** [comment]
What we did today so far: https://github.com/hoodiehq/hoodie-app-mapchat/pull/14

```
- Add hoodie/client.js
 - When a user signs up, it will also sign you in
 - Replace .done with .then
 - Replace .fail with .catch
 - Use new hoodie/client.js file name
 - No longer need Hoodie initialized
 - Rename www to public
 - Remove previous dependencies from package.json
```

**Comment by gr2m** [comment]
I’d love to finish this up some time :) Maybe we can find a day in the next two weeks to pair on this?

**Comment by machikoyasuda** [comment]
Yes <3 Sun. Oct. 16th!

**Comment by gr2m** [comment]
great idea :)

**Comment by gr2m** [comment]
I’ll close the issue as it lacks activity for quite some time now. We also still have to find a way to differentiate between local changes made by the user and changes synchronized from remote which is currently blocking the last fixes. Once we have all that we can give this another look :)
