### ISSUE TITLE
Proofread Camp Docs 📝

### ISSUE THREAD

**Issue by jennwrites** [hoodiehq/camp#15]
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s reserved for participants of [OSCON Contribute](https://ti.to/hoodie/oscon-meet-the-hoodies) until May 20th, 2016. 
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

Strong command of English language/grammar. Knowledge of code (JavaScript, Node.js) is not essential, but helpful. 
### 🐞 The Issue

Proofread and suggest corrections to the new Camp documentation found here: http://docs.hood.ie/camp/.
### :dart: The goal

Finding typos, formatting errors, etc. – any small error that might distract a new contributor when trying to learn from the new documentation.

Helpful resource: [our glossary of commonly used terms](https://github.com/hoodiehq/editorial/wiki/Glossary-of-common-terms). Double check your references to popular tech lingo here. 
### :clipboard: Step by Step
- [x] **claim this issue**  
  comment below. Once claimed we add you as contributor to this repository, so we can assign you to the ticket and you can start checking off the checkboxes below as you progress. We will also replace the `ready` label with `in progress`.
- [x] **Review** the documentation beginning on the [welcoming page](http://docs.hood.ie/camp/.) all the way through the [glossary](http://docs.hood.ie/camp/hoodieverse/glossary.html). 
- [x] **Start a Pull Request**. hoodiehq/documentation#219 
- [x] **Done** :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by rossyoung5** [comment]
Hey I'd like to claim this issue. Thanks!

**Comment by jennwrites** [comment]
It's yours @rossyoung5!

**Comment by rossyoung5** [comment]
For the documentation, what do I need to actually fork/edit? There's just an empty html doc in the repo.

**Comment by gr2m** [comment]
@rossyoung5 the repository is https://github.com/hoodiehq/documentation. All the content for the Camp Docs are the `*.md` files in https://github.com/hoodiehq/documentation/tree/gh-pages/camp – does that work for you?

**Comment by rossyoung5** [comment]
That works! Thanks.

**Comment by CrowdHailer** [comment]
hey hey, hows this issue getting along. I'm certainly up for proof reading. @rossyoung5 you still claiming this issue and the guy to talk to

**Comment by gr2m** [comment]
I think @rossyoung5 finished his review via https://github.com/hoodiehq/documentation/pull/219, and we only forgot to close the issue? Or is there something left to be reviewed from your side @rossyoung5? Sorry we missed to update the issue when https://github.com/hoodiehq/documentation/pull/219 landed

**Comment by rossyoung5** [comment]
Yeah I think I had finished up at 219, so I guess it was just never closed.

**Comment by gr2m** [comment]
Thanks again for your help Ross, and sorry for missing that!

Closed via https://github.com/hoodiehq/camp/issues/15
