### ISSUE TITLE
Create a Wikipedia entry for Hoodie

### ISSUE THREAD

**Issue by jennwrites** [hoodiehq/camp#16]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

How to add/edit entries for [Wikipedia](https://en.wikipedia.org/wiki/Main_Page), as noted here [Your first article](https://en.wikipedia.org/wiki/Wikipedia:Your_first_article) and [Article development](https://en.wikipedia.org/wiki/Wikipedia:Article_development).
### 🐞 The Issue

There's no Wikipedia entry for Hoodie.
### :dart: The goal

Create an entry for Hoodie! 🐶 
### :clipboard: Step by Step
- [x] **claim this issue** @etopiei
- [x] Familiarize yourself with the Wikipedia publication process.
- [ ] Write a draft of an article for Hoodie 
- [ ] Get feedback on the article from the editorial team 
- [ ] Submit to Wikipedia 
- [ ] **Done** :+1: Replace `up for grabs` label with the `ready` label and ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by kamon-harrell** [comment]
Claimed

**Comment by etopiei** [comment]
I'd be happy to write up a wikipedia article about Hoodie.

**Comment by gr2m** [comment]
That’s great @etopiei, welcome to Hoodie :) if you have questions about the project, I’m happy help as good as I can. I’m one of the founding contributors to the project

**Comment by gr2m** [comment]
@etopiei are you still working on it?

**Comment by etopiei** [comment]
Yeah, been a bit hectic recently, but I'm hoping to have a draft done by the end of the weekend.

**Comment by gr2m** [comment]
Great, thanks for the update @etopiei

**Comment by etopiei** [comment]
Taking a look at the wikipedia criteria for article creation over the weekend, I don't know if an article on hoodie would be given the green light. I can't find too many links to it to use as citations.

**Comment by gr2m** [comment]
I’d say even if it does not get accepted, maybe you can create a draft in a google doc or somewhere that we can use as a base of discussion and review, before submitting it to Wikipedia?

I think we have a few articles, like https://opensource.com/life/16/2/hoodie-open-source-community. 

@janl @renrutnnej @skeskali @Charlotteis can you think of other articles we could cite in a wikipedia article?

**Comment by gr2m** [comment]
this is done: https://en.wikipedia.org/wiki/Hoodie_(software)
