### ISSUE TITLE
🐦 Update Twitter, background and avatar 

### ISSUE THREAD

**Issue by jennwrites** [hoodiehq/camp#17]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

Photoshop or equivalent photo-editing software. 
### 🐞 The Issue

A good time to start promoting the Camp Release, as we will host a hackathon as part of EmpireJS week: https://ti.to/hoodie/nyc-meet-the-hoodies-3

Here are source files for a super nice Hoodie Camp illustration: https://www.dropbox.com/sh/ulympy8huj3asnf/AAAPCmgYhio0hATsSLTsEFfHa?dl=0 – shall we use that in the Twitter header? Maybe replacing the current image entirely, or just a few squares as we did in https://github.com/hoodiehq/editorial/issues/60? 

We could also update the avatar to remove the hat :) Birthday is over. Here is Low Profile dog without the hat: https://dl.dropboxusercontent.com/u/732913/hoodie/low-profile-dog.png

Would be great if someone could help with it. Any objections?
### :dart: The goal

Promote Hoodie Camp at [EmpireJS](http://2016.empirejs.org/)! 🎉 
### :clipboard: Step by Step
- [x] **claim this issue**: @norkuy
- [x] Make changes to source files above.
- [x] Submit links to updated source files here by commenting below! 
- [x] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by norkuy** [comment]
I'll take a shot at it.
avatar:
https://www.dropbox.com/s/vo3cmtsiziak0u6/avatar.png?dl=0
header:
https://www.dropbox.com/s/ocv9o8q7d68l49u/twitterHeader.png?dl=0

**Comment by gr2m** [comment]
I’m so sorry @norkuy we never got back to you :( Thanks a lot for creating these graphics! I’d vote for making the header background a solid color and just showing the tent illustration. Any thoughts @renrutnnej @espy @hoodiehq/maintainers?

**Comment by norkuy** [comment]
No problem @gr2m. Happy to help. I can put the tent illustration on a white background if that works. Thanks

**Comment by machikoyasuda** [comment]
@norkuy These are so cute <3 I second @gr2m's idea of the tent illustration on a white background 👍

**Comment by gr2m** [comment]
@norkuy yeah that would be great, thanks :)

**Comment by norkuy** [comment]
@gr2m Here you go :)
Twitter Header:
https://www.dropbox.com/s/gl0nwrwfy8boo2n/twitterHeader.png?dl=0

**Comment by gr2m** [comment]
Nice :) Thanks @norkuy! This looks great: https://twitter.com/hoodiehq

I’ve invited you to the Hoodie Contributors Team, welcome :)

Are you on twitter? We like giving shoutouts to our new contributors. Only if you like of course

**Comment by norkuy** [comment]
sure @gr2m my name is @JeffMignone. Thank you for the invite!
