### ISSUE TITLE
What could be a useful UI if an app has no `public/` folder

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#19]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### 🤔 What you will need to know

Hoodie is a generic backend for your application, but can also serve your static html application. The latter is not required, it’s a common use case that people run their Hoodie Server somewhere like https://myhoodieapp.com` and the static app is served directly from GitHub pages or [surge.s](http://surge.sh/) or another hoster for [static apps](https://staticapps.org/). In that case, when opening the URL of the Hoodie Server should show some generic fallback UI.
### :dart: The goal

What could we show in this generic Hoodie UI? Maybe the version? Maybe an explenation of what it is? Maybe link to the other generic UIs at `/hoodie`, `/hoodie/account` and `/hoodie/store`? Maybe we should directly show the admin UI that is usually at `/hoodie/admin`? We are open for ideas

This is not really a bug that needs to be fixed or a feature that needs to be implement, but an invite for a discussion. Please ask all your questions here, we are looking forward for your thoughts! Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by cheapwebmonkey** [comment]
I would have all of the following: version, explanation,  link to the other generic UIs @ /hoodie, /hoodie/account and /hoodie/store.

**Comment by gr2m** [comment]
Sounds good :) would you like to give it a go? Happy to chat, too, if you have any questions?

**Comment by gr2m** [comment]
@cheapwebmonkey from what you said, I think you want to work on the 3 issues #20 / #21 / #22, right? This issue is not about the `/hoodie` path, which all apps will have, but about what will be shown at the root path if the app has no `public/` folder. Does that make sense? I’m happy to assign you to #20, #21 and #22, and happy to chat with you on what these UIs might look like and how they could work together?

**Comment by kouryuu** [comment]
Hi, I too have interest in this issue I proposed the following interface to the Slack group http://codepen.io/kouryuu/full/VKzkqL/ and to @gr2m  now this is intended for when the`/public` is missing and we need another for the root page of hoodie #8 which seems to be assigned to @distalx perhaps we can all work together and combat all issues related with missing UI :)

**Comment by cheapwebmonkey** [comment]
Sounds good

Margeaux Spring
GitHub.com/cheapwebmonkey

**Comment by gr2m** [comment]
> perhaps we can all work together and combat all issues related with missing UI :)

I’d love that. And happy to help / coordinate our effortts :) /cc @distalx

**Comment by gr2m** [comment]
@cheapwebmonkey @distalx could you join our slack chat at http://hood.ie/chat/ if you haven’t yet? It would make the coordination a bit simpler. I’m `@gregor` in the chat, I’ll create a channel for us :)
