### ISSUE TITLE
npm start -- setup

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#2]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### 🤔 What you will need to know

JavaScript, Node.js. Knowledge about `npm` would be helpful but are not required.
### ❓ The Motivation

We try to integrate very tightly with `npm` and its eco system. Instead of creating our own [CLI](https://en.wikipedia.org/wiki/Command-line_interface) tool, we want to use `npm` directly. At this point we only use the `npm start` script to start the Hoodie Server, in future we might want to have all kind of commands like `npm start setup`, `npm start console`, etc. 
### :dart: The goal

When running `npm start setup`, the Hoodie Server should _not_ get started. Instead the following things should happen:
1. Create a `README.md` unless it already exists. Put in dummy content for now
2. Set the "start" script in `package.json` to `"hoodie"` (see [setup instructions](https://github.com/hoodiehq/hoodie#setup))
### :clipboard: Step by Step
- [x] claim this issue (comment below or assign yourself if you can)
- [x] [Setup the hoodie repository locally](https://github.com/hoodiehq/hoodie#testing) and make sure that all tests pass
- [x] Implement the feature. `hoodie` executes the binary which is [hoodie/bin/start.js](https://github.com/hoodiehq/hoodie/blob/master/bin/start.js) as defined [here](https://github.com/hoodiehq/hoodie/blob/26016aabf8ab17935561264e14d3954dd821e6ba/package.json#L6-L8). Instead of calling the `cli` function, check if the `setup` argument was passed and if yes, do the setup as described :) A first step (and commit) could be a `console.log('setup')`, to get a pull request going. 
- [x] Commit with `feat: hoodie setup`  
  Don’t worry about wording or amount of commits. We will clean up everything before we merge :)
- [x] Start a Pull Request. Mention `closes hoodiehq/camp#2` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [x] Done :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by boennemann** [comment]
To clear up possible confusion, @gr2m, do you want to go for `npm start setup`, or `npm start -- setup`?
The first one would require reparsing npm's arguments and might lead to confusion and significant edge case handling. The second option would be the npm way of doing things, but of course it's a bit weird to type.

**Comment by gr2m** [comment]
What could be the side effects of `npm start setup` being handled by hoodie? I’ve seen @kentcdodds doing it at https://github.com/kentcdodds/p-s and thought this is pretty cool

**Comment by kentcdodds** [comment]
In case it's useful, here's a brief explanation of why I use `start`: https://github.com/kentcdodds/p-s#why-npm-start

**Comment by kellyjandrews** [comment]
I'll do this one as well, if I'm already doing #1

**Comment by gr2m** [comment]
Hey @kellyjandrews, I invited you to the repo so we can assign you to the issue: https://github.com/hoodiehq/camp/invitations

I would suggest you do this issue first but just with `npm start -- setup`, it is what we need the most right now. Once we have that, let’s chat on creating the alias like `npm start setup` for `npm start -- setup` and `npm start help` for `npm start -- help` — does that work for you?

**Comment by kellyjandrews** [comment]
That works for me - also #7 seems related. Trying to determine the best approach here - but I assume simply adding another dep here isn't what's desired.

**Comment by gr2m** [comment]
I’ve altered #7 for now to only implement `npm start -- console` for now. 

The alias for `npm start xyz` is just a nice to have. I’d like to give it a try to see how complex it would be, but if it adds to much complexity I’d be okay to stick with `npm start -- xyz`.

**Comment by kellyjandrews** [comment]
Parsing the arguments is actually fairly easy here.  

```
if (process.argv.length < 3) {
  console.log("Start Server");
  startServer();
} else {
  console.log("Do Something Else");
}
```

Should be straight forward to have `npm start setup` but still trying things out to see how they work.

**Comment by gr2m** [comment]
sounds good 👍 Don’t worry about starting a pull request with work-in-progress, most of our pull requests are "messy" in a good way, we only clean them up before we merge it, that’s why the commit history looks so clean :)

**Comment by gr2m** [comment]
Hey @kellyjandrews how is it going?

**Comment by kellyjandrews** [comment]
Slower than expected. Working on it right now though - I'll keep you posted.

**Comment by gr2m** [comment]
thanks! I might be slow giving feedback this week as I’m at http://opensourcebridge.org/ and http://offlinefirst.org/camp/, but will do my best to help with any questions. Feel free to ping people in http://hood.ie/chat/, there usually are people around :)

**Comment by kellyjandrews** [comment]
Will do - submitting a PR now for the initial argument flow suggestion.  I will have a few questions, and I'll use the chat channels to get those answered. Thanks!

**Comment by gr2m** [comment]
The issue is up for grabs again :)

**Comment by gr2m** [comment]
Ignore the issue history above, this issue is up for grabs again :)

**Comment by klazich** [comment]
I'd like to give this a shot. This would be my first time working on a project outside of a online courses and challenges. If there is a different issue better suited for a beginner i'll claim that one. Or, just tell me to go the hell away and i'll understand :) Good luck with hoodie!

**Comment by gr2m** [comment]
Nobody will ever tell you do go away as long as you are nice to us :) it's all yours! Let us know if you need any help! Welcome at Hoodie :)

**Comment by klazich** [comment]
Good to hear! I'll get started.

**Comment by klazich** [comment]
I'll hopefully have something in the next few days. It's been a busy work week so I haven't had much time to look at it.

**Comment by gr2m** [comment]
No worries, keep us posted :)

**Comment by klazich** [comment]
So, here is what I have so far:

```
// a-script.js
// writes to parent package.json. Used here to set a "start" script
#!/usr/bin/env node

var fs = require('fs');
var fileName = '../../package.json';
var file = require(fileName);

file.scripts = file.scripts || {};
file.scripts["start"] = "echo \"success\"";

fs.writeFile(fileName, JSON.stringify(file, null, 2), function(err) {
    if (err) return console.log(err);
});
```

With this script set to run on package `"install"` (or any `"install"` lifecycle event) I can set the parent `package.json` `"start"` script. 

I was thinking of using this to set the `"prestart"` hook to run a file that listens to `process.argv` for passed commands (or `process.env` for lifecycle events). So `npm start setup` can still set `"start"` to `"hoodie"` and still allow for additional `"start"` commands in the future.

Does that sound like the direction you want to go?

**Comment by gr2m** [comment]
Yeah that sounds good! I just realized that the idea of `npm start -- setup` to set the package.json’s start script doesn’t make much sense because unless it’s set we can’t run `npm start` :facepalm: :) Sorry for the confusion. So I think you pretty much work on this issue and #3 at the same time, which is graet

I would suggest we run your script in `postinstall`. Three
1. `var fileName = '../../package.json';` won’t work on windows, try to avoid to hard code path separators. Please use [path.join](https://nodejs.org/api/path.html#path_path_join_path) instead
2. Check if the user run `npm install --save hoodie` or `npm install -S hoodie`, and only run the setup then. 
3. Maybe add a `console.log('Start your Hoodie app with "npm start"')` to the end?

**Comment by klazich** [comment]
So use path like this?: 

```
path.join('..','..','package.json')
```

Sorry, still fairly new to Node.

Also, will the `package.json` we want to target always be 2 above where the script executes? I was hoping there would be some other way to get the project root but didn't find anything.

**Comment by gr2m** [comment]
yes that looks right.

Your comment is right though, there might be edge cases where the target is not exactly 2 directories above the Hoodie code. Alternatively you can also do `path.join(process.cwd(), 'package.json')`. `process.cwd()` returns the full path of the directory you run the `npm install` command from, so it acchieves the same thing. Maybe let’s use that?

**Comment by gr2m** [comment]
Also no need to excuse, happy to help :)
