### ISSUE TITLE
Review Camp App tutorial

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#23]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

We created a tutorial in form of a web page that uses Hoodie & ServiceWorker to show how to build an offline app. The source code is at https://github.com/hoodiehq/hoodie-camp-tutorial, you can test it out online at https://camp-tutorial.hood.ie/.
### :dart: The goal

We created this tutorial in a hurry and we are not native English Speakers, nor do we have much experience in technical writing. It would be great if you could help us by reviewing it.

Feel free to edit the pages directly on GitHub and send pull requests with suggestions. All html pages are here: https://github.com/hoodiehq/hoodie-camp-tutorial/tree/master/public, you can edit them directly in your browse (click on one of them, then click the edit icon on top right, make your change, click the button "Propose File Change" then click "Start Pull Request".

If you have any questions or have ideas, we can discuss in this issue, comment below

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by jorydotcom** [comment]
Note: The live tutorial at [http://camp-tutorial.hood.ie](http://camp-tutorial.hood.ie) is throwing a 502 error

**Comment by jorydotcom** [comment]
I've been reading through this and have some ideas for updates/polish, but have some questions before I go crazy:
- does this need to be a bootstrap app? 
- are there other tutorial sites for hoodie, or will this be the primary tutorial app?
- do you imagine wanting to expand this tutorial to include other learning objectives?

Other rando thoughts as I look at this: 
- tutorial should reference/support/augment the '[how hoodie works](http://docs.hood.ie/en/hoodieverse/how-hoodie-works.html)' doc section
- how much knowledge do we want to assume people have coming in (not much, is my guess?) - are there other tutorials/how-tos we should link to for like, what service workers are, for example?

**Comment by gr2m** [comment]
> Note: The live tutorial at http://camp-tutorial.hood.ie is throwing a 502 error

that’s fixed now, thanks :)

> does this need to be a bootstrap app?

no :)

> are there other tutorial sites for hoodie, or will this be the primary tutorial app?

This is the first tutorial app we have so far. It’s special as it also introduces ServiceWorker, to create an app that fully works offline.

> do you imagine wanting to expand this tutorial to include other learning objectives?

I don’t think so, I’d focus in on its scope, and create other tutorials for other objectives?

> tutorial should reference/support/augment the 'how hoodie works' doc section

I dunno how yet, but we are very open to your suggestions

> how much knowledge do we want to assume people have coming in (not much, is my guess?) - are there other tutorials/how-tos we should link to for like, what service workers are, for example?

Good point. I don’t know any out of my head, but if you find one, let’s link it :)

**Comment by gr2m** [comment]
Hey @jorydotcom, do you want to continue to work on this?

**Comment by gr2m** [comment]
This issue is up for grabs again :)

**Comment by machikoyasuda** [comment]
I will take this issue. Nervous and excited to learn about ServiceWorkers 😊✨

**Comment by gr2m** [comment]
all yours :) enjoy

**Comment by gr2m** [comment]
@machikoyasuda can we close this one?

**Comment by machikoyasuda** [comment]
yes

On Thu, Nov 3, 2016 at 8:48 PM -0700, "Gregor Martynus" notifications@github.com wrote:

@machikoyasuda can we close this one?
