### ISSUE TITLE
Update "Getting started with Hoodie - Part 2" tutorial to the Hoodie Camp Release

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#25]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### :dart: The goal

The current tutorial is empty: http://docs.hood.ie/camp/tutorials/, the docs for the old Hoodie are at http://docs.hood.ie/en/tutorials/. It would be great if we could update it for the new Hoodie. Maybe helpful to see what APIs changed is the diff from the current migration of our [Hoodie Skeleton App](https://github.com/hoodiehq/hoodie-app-skeleton/compare/master...camp)
### :clipboard: Step by Step
- [ ] **claim this issue**: @tinyinkling
- [ ] **Update the tutorial** :) Even if it’s work in progress, you can start a pull request for https://github.com/hoodiehq/documentation/blob/gh-pages/camp/tutorials/index.md. You can do that right from the browser: click on the edit icon on top right, make your changes, then at the bottom of the page click "Propose File Change" and then "Start Pull Request"
- [ ] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by tinyinkling** [comment]
Inspired by the talk yesterday at CascadiaFest by @gr2m - I'd like to claim this issue and work on the docs!

**Comment by gr2m** [comment]
That’s great Brooke, welcome :) Please find me if you have any questions, I’d be more than happy to give you an overview of things.

**Comment by gr2m** [comment]
Hey @tinyinkling, how are things going? Anything we can help with?

**Comment by gr2m** [comment]
🔔 ping @tinyinkling :) Make sure to sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) before sending a pull request :)

**Comment by gr2m** [comment]
🔔 ping @tinyinkling let me know if you still want to work on this, otherwise we can free it up for someone else to work on

**Comment by pinglinh** [comment]
Hi I did a pull request for this at https://github.com/hoodiehq/documentation/pull/245 I hope it's okay? Let me know of any changes to be made :bowing_woman:

**Comment by gr2m** [comment]
Hey @pinglinh we consolidated our documentation, it now lives at https://github.com/hoodiehq/hoodie/tree/master/docs and is hosted at http://hoodie.readthedocs.io. The original 

The "" is still accessible at https://github.com/hoodiehq/documentation/blob/gh-pages/en/tutorials/index.md. It would still be cool to update the tutorial for the new Hoodie. If you’re still interested to work on it? I’m happy to coach to you trough the process :)

**Comment by gr2m** [comment]
I’ll close this issue for now. We’ll open up other opportunities to write tutorials for Hoodie and related projects, stay tuned :)
