### ISSUE TITLE
Fix tests in hoodie-store

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#29]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### 🤔 What you will need to know

`hoodie-store` is one of the core components of [Hoodie’s architecture](https://github.com/hoodiehq/hoodie/tree/master/server#store-octocat--). It integrates [the Store Server](https://github.com/hoodiehq/hoodie-store-server#readme) and [the Store Client](https://github.com/hoodiehq/hoodie-store-client#readme). It has a demo built in that you can run with `npm start`, it will show a html page that loads the store client for testing. This demo server is also used for testing.

For testing we use a module called [frontend-test-setup](https://github.com/gr2m/frontend-test-setup), which uses [selenium](http://docs.seleniumhq.org/), [webdriver](), [mocha](mocha) and [chai]() and start a server and then remote control real browsers to run so called [end-to-end tests](https://en.wikipedia.org/wiki/Software_testing#System_testing) tests. The tests are defined in [hoodie-store/test/integration.js](https://github.com/hoodiehq/hoodie-store/blob/aa3af84/test/integration.js). For example, here is [the test for store.isConnected](https://github.com/hoodiehq/hoodie-store/blob/aa3af84/test/integration.js#L53-L73)
### 🐞 The Bug

Two tests are currently failing, see [this travis build](https://travis-ci.org/hoodiehq/hoodie-store/builds/133209242#L251). We don’t know what change introduce the issue, but besides having a potential bug in Hoodie, having failing tests is very inconvenient as we automate our dependency updates with [Greenkeeper](https://greenkeeper.io/), and each time there is an update of any dependency and the test fail, Greenkeeper starts a pull request because it thinks that the update broke `hoodie-store`, while the reason for the failing test is not related to the new module at all. So we get a lot of [false positives like this one](https://github.com/hoodiehq/hoodie-store/pull/15).
### :dart: The goal

Figure out what the issue is. It might be the tests or the implementation in `hoodie-store-server`, `hoodie-store-client`, `pouchdb-hoodie-api` or `pouchdb-hoodie-sync`. 
### :clipboard: Step by Step
- [x] **Claim this issue**: @alanmbarr
- [x] [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-store#testing) and make sure that you have the same failing tests as in  [this travis build](https://travis-ci.org/hoodiehq/hoodie-store/builds/133209242#L251).
- [x] Figure out what the issue is and fix it in the respective repository. Don’t worry about commit messages, we can clean them up before merging your pull request. 
- [x] **Start a Pull Request**: https://github.com/hoodiehq/hoodie-store/pull/17
- [x] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by alanmbarr** [comment]
Hi I would like to claim this issue.

**Comment by gr2m** [comment]
All yours :) I’ve invited you to the repo, you can accept the invitation at https://github.com/hoodiehq/camp/invitations. Once accepted, you can check of the steps above as you go

**Comment by alanmbarr** [comment]
I sent a pull request but sauce couldn't connect :(

**Comment by gr2m** [comment]
> I sent a pull request but sauce couldn't connect :(

Our fault, it was not setup correctly. Should work now

**Comment by gr2m** [comment]
Thanks for taking the time and resolving the issue, once a 2nd maintainers gives their `LGTM` we can merge it in. 

Welcome at Hoodie 🎉 I’ve invited you to Hoodie’s Contributors team :) Are you on twitter? We love giving shout-outs to new contributors

I hope you like working on the problem. If you have any feedback, please let us know :) If you like to work on something else, please feel free to grab another one of the prepared [camp issues](https://github.com/hoodiehq/camp/issues?q=is%3Aissue+is%3Aopen+label%3A%22up+for+grabs%22). 

There is also a somewhat similar issue for the account-module: https://github.com/hoodiehq/hoodie-account/issues/3 – it’s more tricky though, as tests only work sometimes, looks like a racing condition.

**Comment by alanmbarr** [comment]
you can give me a shoutout at @alanmbarr on twitter
