### ISSUE TITLE
use standard universallay unique IDs for account IDs

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#31]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who
did not yet contribute to Hoodie to work on this issue. Follow
[@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of
these issues across many open source projects :)
### 🤔 What you will need to know

Node.js
### ❓ The Motivation

Once your Hoodie app reaches a billion user accounts, the likability of id conflicts becomes to high. So before you build the next Facebook with Hoodie, let’s fix this first ;)
### :dart: The goal

The current implementation is here: https://github.com/hoodiehq/hoodie-account-server/blob/master/api/accounts/add.js#L13-L15. It uses 12 random hex characters. 

What we think makes sense is to follow the convention, see https://en.wikipedia.org/wiki/Universally_unique_identifier. 
### :clipboard: Step by Step
- [x] **Claim this issue**:  @akhillb
- [x] [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server/blob/master/tests/README.md#testing) Ensure the tests pass, or docs build...
- [x] Replace the ID generation currently using random string with something that generates a conventional universally unique identifier (version 4). For example, you can use [uuid.v4()](https://www.npmjs.com/package/uuid) for that, but we are open for suggestions.
- [x] **Commit** with `fix: UUID for account id`
- [x] **Start a Pull Request**. https://github.com/hoodiehq/hoodie-account-server/pull/185
- [ ] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by akhillb** [comment]
Hey I would like to work on this.

**Comment by gr2m** [comment]
great, all yours @akhillb

**Comment by gr2m** [comment]
how are things going @akhillb? Is there anything we can help with?

**Comment by ohiock** [comment]
Hi @gr2m - I saw this issue had been sitting for some time and decided to take a stab at it. I hope that's not an issue. I submitted a PR but I assume I cannot update this issue since I'm not the assignee? (sorry, I'm a noob) It's PR #185.

**Comment by gr2m** [comment]
no that’s totally fine, thanks! I’ll have alook at your pull request right away :)
