### ISSUE TITLE
SSL for the deployed site

### ISSUE THREAD

**Issue by NickColley** [hoodiehq/camp#34]
Is it possible to enable https for github pages?

**Comment by varjmes** [comment]
@nickcolley https is on github pages by default

eg https://charlotteis.github.io/ (bad, old site) i didn't set it to do anything

**Comment by NickColley** [comment]
Yeah just thinking of http://hoodie.camp/

**Comment by varjmes** [comment]
ohhhhhhhh by bad. sorry.

**Comment by gr2m** [comment]
Good question though, I think there was a way to do it with some CDN provider? Hmmm maybe I just dreamed it though :)

**Comment by gr2m** [comment]
looks like Cloudflare is the way to go:
https://twitter.com/gr2m/status/780247514830086144

**Comment by christophwitzko** [comment]
@gr2m If you need any help with cloudflare, let me know.

**Comment by gr2m** [comment]
@christophwitzko if you could set this up, that’d be fantastic :)

**Comment by gr2m** [comment]
Thanks @christophwitzko for setting up everything! We should do the same for hood.ie if this works well :) Check out https://hoodie.camp y’all! 👀
