### ISSUE TITLE
🎃🕵💻 Update hoodie to latest good

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#35]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### 🎃🙀👕🎓😻 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process 
### 🤔 What you will need to know

Node.js, [hapi](http://hapijs.com/) and [good](https://www.npmjs.com/package/good). 

`hapi` is a server plugin that we use for all of Hoodie’s server bits. `good` is a hapi plugin for logging. We use [npmlog](https://www.npmjs.com/package/npmlog) for setting the log level and for logging warnings, errors etc. We combine the two at https://github.com/hoodiehq/hoodie/blob/master/server/plugins/logger.js.
### ❓ The Motivation

A [new version of good](https://github.com/hapijs/good/issues/467) has been released a while ago, and we did not yet managed to update to it. The API has changed. 
### :clipboard: Step by Step
- [x] **Claim this issue**: Comment below or assign yourself and continue at step 3 :)  
  Please 🙏  only claim if you want to start working on it within a day.  
  Once claimed we add you as contributor to this repository. 
- [x] Accept our invitation to this repository. Once accepted, assign yourself to this repository
- [x] replace the `up for grabs` label with `in progress`.
- [x] [**Setup the hoodie repository locally**](https://github.com/hoodiehq/hoodie/#testing) Make sure that all tests are passing
- [x] For testing the logging, run `npm start -- --inMemory --loglevel=info`. You should see `info log 2016-10-02T01:08:45.320Z [ 'hapi' ] hoodie core plugins registered` 
  <img width="761" alt="screen shot 2016-10-01 at 18 09 12" src="https://cloud.githubusercontent.com/assets/39992/19017895/3e069a4a-8802-11e6-8d6a-b3ba320cf215.png">
- [x] **Update to good@7.0.2**. You can do so with `npm install good@7.0.2 --save`
- [x] Adapt the usage of `good` for the new version. See the [Good 7.0.0 Release Notes](https://github.com/hapijs/good/issues/467).
- [x] **Commit** with `good@7.0.2` or whatever you like :)
- [x] **Start a Pull Request**. https://github.com/hoodiehq/hoodie/pull/598
- [x] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by joselitojunior1** [comment]
🚀

**Comment by dontrebootme** [comment]
I can try this one.

**Comment by gr2m** [comment]
Awesome, I’ve invited you to the repository. Good luck, it’s all yours 🙌

**Comment by Rishabh8871** [comment]
Hactoberfest it is..  Can i try!!

**Comment by jsoranno** [comment]
Next on the list :)

**Comment by gr2m** [comment]
@Rishabh8871 @jsoranno we will create more issues like these troughout October, if you want to get notified you can watch this repository :)

**Comment by Subway19** [comment]
I would like to claim this. This would be my first open source pull request.

**Comment by dontrebootme** [comment]
@Rishabh8871 @jsoranno @Subway19 feel free to take this one. It seems the work involved is more complicated than I initially understood and probably best if someone else has better experience with Node, Hapi and Good.

**Comment by gr2m** [comment]
Thanks for trying @dontrebootme 👍 

To everyone who wants to give this a try: this issue is not suitable for JavaScript beginners, ideally you have already built applications with hapi before, it’s quite complex.

**Comment by mbad0la** [comment]
Hey @gr2m how much time would it take to get a hang of hapi?
I'm quite comfortable with JavaScript but haven't hacked around with hapi before.

**Comment by varjmes** [comment]
All those interested: only one person can do the issue, please make sure to check if the issue has been claimed, before telling us you will do it. @dontrebootme said they were unable to do it, which means now the issue is up for grabs. Looks like @Rishabh8871 was second in line to claim this. If Rishabh does not want to do it, then @jsoranno can claim it. If @jsoranno doesn't want to do it, then @mbad0la can give it a go.

**Comment by gr2m** [comment]
@mbad0la I’d say you can probably built something with it within a few hours? I can really recommend to check it out anyway: http://hapijs.com/ – it’s fantastic, very mature framework. You can learn a lot from reading its source code, too.

How about you try building a small application with it that also uses the latest `good` for logging to get an understanding of how it works?

**Comment by jyotman94** [comment]
@gr2m hey it seems nobody is working on this issue currently. May I take this issue? I can start right now.

**Comment by eduardoportilho** [comment]
I'm also ready to take it! @gr2m

**Comment by gr2m** [comment]
Thanks @eduardoportilho, @mbad0la is also looking into it right now.

@mbad0la can you start a pull request, even if it’s just work in progress? That way we can start collaborating on it?

@eduardoportilho do you have experience with hapi / good?

**Comment by eduardoportilho** [comment]
@gr2m Not particularly, but I've been working with JS for a while. Do you have any other issues to suggest?

**Comment by danielbayerlein** [comment]
This issue is not to be underestimated. 😉

**Comment by gr2m** [comment]
fyi the pull request is here: https://github.com/hoodiehq/hoodie/pull/598

@mbad0la also note https://github.com/hoodiehq/hoodie/issues/599, not sure if this is relevant for your work at all

**Comment by mbad0la** [comment]
@gr2m I'll probably refer to it once I've identified some of the old methods in the code.
Really pumped up to resolve this :p

**Comment by mbad0la** [comment]
@gr2m please review my PR.
