### ISSUE TITLE
📑🖋 Update LICENSE in hoodie-server repository

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#36]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 Read more about [First Timers Only](http://www.firsttimersonly.com/)
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process
### ❓ The Motivation

GitHub recently released a new feature which [shows the repository’s license on the overview page](https://github.com/blog/2252-license-now-displayed-on-repository-overview). While all of Hoodie’s repositories have a License ([Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0)), it is not displayed on the overview. The reason is that our `LICENSE` files are missing a few parts.
### :dart: The goal

The license should be displayed on [hoodiehq/hoodie-server’s overview page](https://github.com/hoodiehq/hoodie-server) like it is displayed on the [hoodiehq/hoodie repository](https://github.com/hoodiehq/hoodie)

<a href="https://github.com/hoodiehq/hoodie"><img width="981" alt="screen shot 2016-10-02 at 11 12 54" src="https://cloud.githubusercontent.com/assets/39992/19022632/4922944e-8891-11e6-9fa3-39929715053e.png"></a>
### :clipboard: Step by Step
- [x] 🙋 **Claim this issue**: Comment below
  Please 🙏 only claim if you want to start working on it within a day.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 📝 **Edit** [hoodiehq/hoodie-server’s LICENSE file](https://github.com/hoodiehq/hoodie-server/blob/master/LICENSE) and replace its content with the content of [hoodiehq/hoodie’s LICENSE file](https://raw.githubusercontent.com/hoodiehq/hoodie/master/LICENSE).
- [x] 💾 **Commit** your changes with the message `chore(LICENSE): use standard Apache V2.0 text`
- [x] 🔀 **Start a Pull Request**. Set the title to `LICENSE: use standard Apache V2.0 text` and set description to `closes hoodiehq/camp#36. There are two ways how you can start a pull request:
  1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
  2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by nidble** [comment]
I'would enjoy this issue, does it can be possible? Thanks :)

**Comment by LowProfileDog** [comment]
Absolutely, let me invite you to this repository so you can assign yourself and check of the checkboxes above :) You can accept the invitation at https://github.com/hoodiehq/camp/invitations

**Comment by nidble** [comment]
A question... :) Is it a good practice to self marking into "assignees" during issues solving phase? thanks!

**Comment by gr2m** [comment]
@nidble yes it is :) By assigning yourself to the issue, everyone will know that you are working on this issue

**Comment by nidble** [comment]
Awesome... ^_^  @gr2m please, can you review?

**Comment by gr2m** [comment]
Hey @nidble, you have sent the PR to the wrong repository :) This issue is about this file here: https://github.com/hoodiehq/hoodie-server/blob/master/LICENSE

**Comment by nidble** [comment]
Ups! Copy and paste without unit test! :-D thanks for patience!

**Comment by gr2m** [comment]
no worries :)

**Comment by WarEnek** [comment]
Hi. I want working.

**Comment by ghost** [comment]
Can I Pick up this issue? :)

**Comment by gr2m** [comment]
@WarEnek @AkshayGulhane the issue is already claimed, I’m sorry

**Comment by RakshithNM** [comment]
I would like to make my first OS contribution on this, Please guide me.

**Comment by gr2m** [comment]
@RakshithNM check out http://www.firsttimersonly.com/ and the references linked there. We don’t have any open issues for beginners right now, I’m afraid

**Comment by ghost** [comment]
Hello, 
Can I contribute ? :)

**Comment by saksham-s** [comment]
Hello this is my first time on git.Is it possible for me to work on this issue?

**Comment by samgzl** [comment]
Hello! I'd like to work on the issue if possible :)

**Comment by gr2m** [comment]
@nidble are you still doing it (https://github.com/hoodiehq/camp/issues/36#issuecomment-250989660) or shall we have someone else do the PR?

**Comment by twogoodarms** [comment]
would love the practice!

**Comment by sunidhichaudhary** [comment]
hi ! i would like to work on this issue as i am also a first timer

**Comment by gr2m** [comment]
@sunidhichaudhary I’ve invited you to the repository, you can accept the invite here: https://github.com/hoodiehq/camp/invitations Once accepted you can assign yourself and start working on the issue :)

Sorry for the others, I’ve thrown a cube and Sunidhi won :)

**Comment by sunidhichaudhary** [comment]
Thank you so much for the opportunity. As i am a first timer,it means a lot
to me :) i just want to know whether you received my pull request or there
is a procedure between sending a pull request and  receiving it? thanks:)

**Comment by sunidhichaudhary** [comment]
thanks :)

**Comment by pprintz** [comment]
I would like to work on this issue!

**Comment by gr2m** [comment]
@sunidhichaudhary are you still working on this?

**Comment by nonameable** [comment]
Hello! I'd like to work on it :)

**Comment by gr2m** [comment]
Hey @sunidhichaudhary do you still want to work on this issue? Anyone else?

**Comment by ghost** [comment]
@gr2m I'd like to work on this issue.

**Comment by gr2m** [comment]
@AkshayGulhane okay all yours :)  I’ve invited you to the repository, you can accept the invite here: https://github.com/hoodiehq/camp/invitations Once accepted you can assign yourself start working on the steps above :)

**Comment by ghost** [comment]
@gr2m I have raised a Pull request. Please review my changes. :) 👍
