### ISSUE TITLE
💯 Code Coverage for hoodie

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#4]
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s reserved for participants of [OSCON Contribute](https://ti.to/hoodie/oscon-meet-the-hoodies) until May 20th, 2016. 
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

JavaScript, Node.js. Knowledge about [npm](https://docs.npmjs.com/) would be helpful but are not required, you’ll figure it out as you go :)
### :dart: The goal

100% code coverage makes sure that every single line of code is covered by tests. And it looks pretty cool once we have all the 💯 for all modules in [Hoodie’s Architecture](https://github.com/hoodiehq/hoodie/tree/master/server#architecture)

The current status is [![Coverage Status](https://coveralls.io/repos/hoodiehq/hoodie/badge.svg?branch=master)](https://coveralls.io/r/hoodiehq/hoodie?branch=master)
<img width="855" alt="screen shot 2016-10-01 at 12 30 49" src="https://cloud.githubusercontent.com/assets/39992/19016579/f2ef2c18-87d2-11e6-8fde-ad95ba677c24.png">
### :clipboard: Step by Step
- [x] claim this issue: assign yourself if you are part of the Hoodie team, otherwise comment below :)
- [x] replace `up for grabs` label with `in progress`
- [x] [Setup the hoodie repository locally](https://github.com/hoodiehq/hoodie#testing) and make sure that all tests pass
- [x] Bring coverage to 100%. Use the following steps
  - run `npm test`
  - run `node_modules/.bin/nyc report --reporter=lcov`
  - open `coverage/lcov-report/index.html`. It will look something like this: ![coverage](https://cloud.githubusercontent.com/assets/39992/15349428/4806f9ac-1c98-11e6-87c8-9452c222f499.gif)
- [x] If you are all 100%, commit with `test: 100% coverage`. If you have blockers commit with `test: coverage` and move on, we can discuss details in the pull request
- [x] Start a Pull Request. Mention `closes hoodiehq/camp#4` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [x] Done :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by oluoluoxenfree** [comment]
I'd like to do this one :100:

**Comment by gr2m** [comment]
It’s all yours! Good luck and just in case you get stuck, don’t wait too long, we’re happy to help. Enjoy!

**Comment by gr2m** [comment]
@oluoluoxenfree how are things?

**Comment by oluoluoxenfree** [comment]
A bit stuck on how best to tackle it to be honest!

**Comment by gr2m** [comment]
if you like, ping me in the chat, I’d be happy to help you get unstuck :)

**Comment by gr2m** [comment]
@oluoluoxenfree we are done with our refactoring. Do you want to give it another go?

**Comment by oluoluoxenfree** [comment]
Yes I would! I'll start looking at it on Saturday, thanks so much.

**Comment by gr2m** [comment]
glad to hear :) I’m in LA timezone now so won’t be able to help after ~6pm, but I should be around on Saturday. Otherwise best to ask for help in our chat http://hood.ie/chat/

**Comment by gr2m** [comment]
@oluoluoxenfree 👋

**Comment by oluoluoxenfree** [comment]
Hi! 

Tomorrow I will work on this!! I've been terrible!

**Comment by gr2m** [comment]
I’ll be around after 10am LA time if you have any questions. You can ping me in slack chat :)

**Comment by gr2m** [comment]
... @oluoluoxenfree Hey Olu, we have the [Hacktoberfest](https://hacktoberfest.digitalocean.com/) going and lots of people are looking for issues to work on. I feel really bad to say it but maybe we should let someone else work on it? I don’t want to take it away from you and if you sincerely want to work on this this weekend, I’m happy to help. But if not, I’d like to open it up so someone else can work on it. 

Is that okay with you?

**Comment by oluoluoxenfree** [comment]
Yup that's fine!

**Comment by gr2m** [comment]
All right, this issue is up for grabs again :)

**Comment by davelosert** [comment]
Uhhh... tests. 100% coverage. Sounds EXACTLY like something that I`d like to do.
I'm gonna try to tackle this if it's okay!

**Comment by gr2m** [comment]
absolutely :) I’ve invited you to this repository. Once you accept our invitation, you can assign yourself and start checking off the list above :) Let us know if you have any questions
