### ISSUE TITLE
Update LICENSE in hoodie-account repository 

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#46]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 Read more about [First Timers Only](http://www.firsttimersonly.com/)
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process
### ❓ The Motivation

GitHub recently released a new feature which [shows the repository’s license on the overview page](https://github.com/blog/2252-license-now-displayed-on-repository-overview). While all of Hoodie’s repositories have a License ([Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0)), it is not displayed on the overview. The reason is that our `LICENSE` files are missing a few parts.
### :dart: The goal

The license should be displayed on [hoodiehq/hoodie-account’s overview page](https://github.com/hoodiehq/hoodie-account) like it is displayed on the [hoodiehq/hoodie repository](https://github.com/hoodiehq/hoodie)

<a href="https://github.com/hoodiehq/hoodie"><img width="981" alt="screen shot 2016-10-02 at 11 12 54" src="https://cloud.githubusercontent.com/assets/39992/19022632/4922944e-8891-11e6-9fa3-39929715053e.png"></a>
### :clipboard: Step by Step
- [x] 🙋 **Claim this issue**: Comment below
  Please 🙏 only claim if you want to start working on it within a day.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 📝 **Edit** [hoodiehq/hoodie-account’s LICENSE file](https://github.com/hoodiehq/hoodie-account/blob/master/LICENSE) and replace its content with the content of [hoodiehq/hoodie’s LICENSE file](https://raw.githubusercontent.com/hoodiehq/hoodie/master/LICENSE).
- [x] 💾 **Commit** your changes with the message `chore(LICENSE): use standard Apache V2.0 text`
- [x] 🔀 **Start a Pull Request**. Set the title to `LICENSE: use standard Apache V2.0 text` and set description to `closes hoodiehq/camp#46. There are two ways how you can start a pull request:
  1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
  2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by mzishtiaq** [comment]
Hi, can I claim this issue please?

**Comment by LowProfileDog** [comment]
Hey Zeeshan, it looks like you have sent [many pull requests](https://github.com/search?utf8=%E2%9C%93&q=author%3Amzishtiaq+is%3Apr) before? If you don’t mind, we would like to reserve this for someone who is entirely new to GitHub, to give them a chance making their first steps in open source in a nice & safe environment :)

But we will create more issues in future that are not reserved for first time contributors. Best is to look around [our other repositories](https://github.com/hoodiehq/), follow us [on twitter](https://twitter.com/hoodiehq) and watch the camp repository

**Comment by mzishtiaq** [comment]
Oh, I apologise. I guess it was an misinterpretation on my part. I do have many pull requests but all of them were for practice projects that I worked on with my friends. So, I am still looking for first contribution to a real open source project. Sorry to have wasted your time and thank you for your kind response. :)

**Comment by alecmatthews** [comment]
I would like to claim this. This would be my first open source pull request.

**Comment by LowProfileDog** [comment]
@mzishtiaq oh in that case I think it’s fine, we are honoured to be the first Open Source project that you contribute to :)  The issue is all yours! I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

@alec500oo I’m sorry that it didn’t work out for this one, but if you like you can watch this repository or follow us [on twitter](https://twitter.com/hoodiehq), there will be more :)

**Comment by mzishtiaq** [comment]
Thank you. :)

**Comment by Subway19** [comment]
I would like to claim this. This would be my first open source pull request.

**Comment by gr2m** [comment]
@Subway19 please check if an issue has been claimed already, this one is already taken, unfortunately

**Comment by mzishtiaq** [comment]
Forgot to assign myself, sorry :). Please review.

**Comment by gr2m** [comment]
no worries, reviewing now :) You can also check of the check boxes above. No worries for this time, but for the future, this helps to let us know about your progress :)

**Comment by gr2m** [comment]
Thanks Zeeshan 👍 Feel free to look around for more issues, also in the other repositories. You can also [follow us](https://twitter.com/hoodiehq) or our friends [YourFirstPR](https://twitter.com/yourfirstPR) on twitter. 

Oh and it would be really nice if you could star our main repository, that helps even more people to hear about Hoodie :)
https://github.com/hoodiehq/hoodie ⭐️

**Comment by mzishtiaq** [comment]
Thank you, it has been a pleasure and a good learning experience. The guide is really useful and I'll keep your suggestions in mind for any future contributions. :)
