### ISSUE TITLE
Update LICENSE in hoodie-admin repository 

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#48]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 Read more about [First Timers Only](http://www.firsttimersonly.com/)
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process
### ❓ The Motivation

GitHub recently released a new feature which [shows the repository’s license on the overview page](https://github.com/blog/2252-license-now-displayed-on-repository-overview). While all of Hoodie’s repositories have a License ([Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0)), it is not displayed on the overview. The reason is that our `LICENSE` files are missing a few parts.
### :dart: The goal

The license should be displayed on [hoodiehq/hoodie-admin’s overview page](https://github.com/hoodiehq/hoodie-admin) like it is displayed on the [hoodiehq/hoodie repository](https://github.com/hoodiehq/hoodie)

<a href="https://github.com/hoodiehq/hoodie"><img width="981" alt="screen shot 2016-10-02 at 11 12 54" src="https://cloud.githubusercontent.com/assets/39992/19022632/4922944e-8891-11e6-9fa3-39929715053e.png"></a>
### :clipboard: Step by Step
- [x] 🙋 **Claim this issue**: Comment below
  Please 🙏 only claim if you want to start working on it within a day.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 📝 **Edit** [hoodiehq/hoodie-admin’s LICENSE file](https://github.com/hoodiehq/hoodie-admin/blob/master/LICENSE) and replace its content with the content of [hoodiehq/hoodie’s LICENSE file](https://raw.githubusercontent.com/hoodiehq/hoodie/master/LICENSE).
- [x] 💾 **Commit** your changes with the message `chore(LICENSE): use standard Apache V2.0 text`
- [x] 🔀 **Start a Pull Request**. Set the title to `LICENSE: use standard Apache V2.0 text` and set description to `closes hoodiehq/camp#48. There are two ways how you can start a pull request:
  1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
  2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by dimejy2** [comment]
Hey, I'd like to claim this!

**Comment by LowProfileDog** [comment]
Welcome Dimeji, the issue is all yours :) I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

**Comment by nitishkd** [comment]
Hi, is this issue still up for grab? I would like to make my first contribution here.

**Comment by nachiketdhamankar** [comment]
Hey! I am interested too! Is this issue still open?

**Comment by amanmehta-maniac** [comment]
I would also like to work for this. Can I get to be a part?

**Comment by imGurpreetSK** [comment]
Is the issue available for grab?

**Comment by Subway19** [comment]
Is this still open? I would like to claim this.

**Comment by varjmes** [comment]
Hello all, as you can see above, the issue has already been claimed by @dimejy2. If dimejy does not wish to work on it we will pass it on to the next in line. Thanks for your interest in Hoodie!

**Comment by dimejy2** [comment]
Hey, I've created the PR and would like a review :)

**Comment by gr2m** [comment]
Thanks @dimejy2 👍 Congratulations to your first accepted Open Source pull request 👏 

 Please feel free to look around for other issues to work on. You can watch this repository to get notified of new issues, follow us [on twitter](https://twitter.com/hoodiehq) and come say hi in [our chat](http://hood.ie/chat/)

**Comment by dimejy2** [comment]
this is really exciting!
