### ISSUE TITLE
Update LICENSE in hoodie-admin-client repository 

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#49]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 Read more about [First Timers Only](http://www.firsttimersonly.com/)
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process
### ❓ The Motivation

GitHub recently released a new feature which [shows the repository’s license on the overview page](https://github.com/blog/2252-license-now-displayed-on-repository-overview). While all of Hoodie’s repositories have a License ([Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0)), it is not displayed on the overview. The reason is that our `LICENSE` files are missing a few parts.
### :dart: The goal

The license should be displayed on [hoodiehq/hoodie-admin-client’s overview page](https://github.com/hoodiehq/hoodie-admin-client) like it is displayed on the [hoodiehq/hoodie repository](https://github.com/hoodiehq/hoodie)

<a href="https://github.com/hoodiehq/hoodie"><img width="981" alt="screen shot 2016-10-02 at 11 12 54" src="https://cloud.githubusercontent.com/assets/39992/19022632/4922944e-8891-11e6-9fa3-39929715053e.png"></a>
### :clipboard: Step by Step
- [x] 🙋 **Claim this issue**: Comment below
  Please 🙏 only claim if you want to start working on it within a day.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 📝 **Edit** [hoodiehq/hoodie-admin-client’s LICENSE file](https://github.com/hoodiehq/hoodie-admin-client/blob/master/LICENSE) and replace its content with the content of [hoodiehq/hoodie’s LICENSE file](https://raw.githubusercontent.com/hoodiehq/hoodie/master/LICENSE).
- [x] 💾 **Commit** your changes with the message `chore(LICENSE): use standard Apache V2.0 text`
- [x] 🔀 **Start a Pull Request**. Set the title to `LICENSE: use standard Apache V2.0 text` and set description to `closes hoodiehq/camp#49. There are two ways how you can start a pull request:
  1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
  2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by pjhampton** [comment]
Hey, I would love to take this! 😄

**Comment by bradlc** [comment]
Please could I claim this one? :)

**Comment by LowProfileDog** [comment]
Absolutely, welcome Brad! The issue is all yours :) I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

**Comment by bradlc** [comment]
All set! Got a bit excited and forgot to assign myself before starting, sorry 😇

**Comment by gr2m** [comment]
No worries, I’m glad you enjoyed and learned a trick or two? 

Feel free to look around, there are other issues to work on, also on other repositories. You can also follow us [on Twitter](https://twitter.com/hoodiehq) :)
