### ISSUE TITLE
using hoodie as hapi plugin: replace options.db with options.PouchDB

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#51]
### 🤔 What you will need to know

You should be experienced with JavaScript, Node.js and testing. Some knowledge about [hapi.js](http://hapijs.com/) will help, but won’t be required.
### ❓ The Motivation

Hoodie is [very modular](https://github.com/hoodiehq/hoodie/tree/master/server#architecture). You can use the main [hoodie](https://github.com/hoodiehq/hoodie) module standalone or as [hapi plugin](http://hapijs.com/tutorials/plugins). Currently the options passed to the server modules are not coherent. For example, [hoodie accepts `options.db`](https://github.com/hoodiehq/hoodie#hapi-plugin), [hoodie-server accepts `options.PouchDB`](https://github.com/hoodiehq/hoodie-server/#example) and [hoodie-account-server accepts `options.usersDb`](https://github.com/hoodiehq/hoodie-account-server#example). We want to normalise these options across all server modules.

### :dart: The goal

The server modules all interact with a database in one way or another, for which we use [PouchDB](https://pouchdb.com). Currently, `hoodie` accepts `options.db` and turns in internally into `options.PouchDB` [in server/index.js#L19-L59](https://github.com/hoodiehq/hoodie/blob/master/server/index.js#L19-L59). What we want instead is that the register functions defined in `server/index.js` accepts `options.PouchDB`, and all the code should live in [cli](https://github.com/hoodiehq/hoodie/tree/master/cli) instead.

So make sure to not just rename the option itself, but also adapt the code accordingly :)

### :clipboard: Step by Step

- [x] 🙋 **Claim this issue**: Comment below
  Please only claim if you want to start working on it during [the event](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/).
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] If you are an existing Hoodie Contributor, create a new branch. If you are a new contributor, welcome 👋 Please fork [hoodie](https://github.com/hoodiehq/hoodie).  
  Setup the repository locally as described in the testing section. Ensure the tests are all passing.
- [ ] Adapt [test/integration/server-test.js](https://github.com/hoodiehq/hoodie/blob/master/test/integration/server-test.js) to use the new API, tests should now fail. 
- [ ] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#51` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [ ] Make the necessary changes in the code to make the test pass.
- [ ] 🏁 **Done** :+1: Once you think your pull request is ready for a first review, replace the `in progress` label with `ready`. Ask in comments for a review :)

### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by anu0012** [comment]
Hey I want to ask one thing. Do we need to change the function accordingly or just replace options.db with options.PouchDB ?

**Comment by gr2m** [comment]
we need to change the function accordingly

**Comment by gr2m** [comment]
@anu0012 are you still looking into it?

**Comment by jeanhl** [comment]
Claiming for opensourcehours 😃 😃 😃 😃 😃

**Comment by gr2m** [comment]
good luck @jeanhl :) Let me know if you have any questions, I’m in the [Hoodie Chat](http://hood.ie/chat/) for another hour or so

**Comment by Taekyoon** [comment]
@jeanhl Hey, are you still work on this? If you aren't working with this, I want to try this issue

**Comment by jeanhl** [comment]
Go ahead. :)

I look forward to learning from you. 

Jean

**Comment by gr2m** [comment]
that’s done now :) https://github.com/hoodiehq/hoodie/issues/555
