### ISSUE TITLE
💯 Code Coverage for Hoodie Account Server

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#53]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

JavaScript, Node.js. Knowledge about [npm](https://docs.npmjs.com/) would be helpful but are not required, you’ll figure it out as you go :)
### :dart: The goal

100% code coverage makes sure that every single line of code is covered by tests. And it looks pretty cool once we have all the 💯 for all modules in [Hoodie’s Architecture](https://github.com/hoodiehq/hoodie/tree/master/server#architecture)

The current status is [![Coverage Status](https://coveralls.io/repos/hoodiehq/hoodie-account-server/badge.svg?branch=master)](https://coveralls.io/r/hoodiehq/hoodie-account-server?branch=master)
<img width="817" alt="hoodie-account-server-coverage" src="https://cloud.githubusercontent.com/assets/17463029/19099009/15d51026-8a67-11e6-9caf-acc31ab51e6d.png">
### :clipboard: Step by Step
- [ ] 🙋 **Claim this issue**: _Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it within a day.  
  Once claimed we add you as contributor to this repository._
- [ ] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [ ] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [ ] 🔄 **replace** the `up for grabs` label with `in progress`.
- [ ] [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server/tree/master/tests) Ensure the tests pass
- [ ] Bring coverage to 100%. Use the following steps
  - run `node_modules/.bin/nyc report --reporter=lcov`
  - open `coverage/lcov-report/index.html`. It will look something like this: ![coverage](https://cloud.githubusercontent.com/assets/39992/15349428/4806f9ac-1c98-11e6-87c8-9452c222f499.gif)
  - ProTip™: run a single test with `node_modules/.bin/tap tests/integration/api/accounts-test.js`
  - If you get stuck or have any questions, start a pull request, that will help
    with the discussion
- [ ] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#53` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [ ] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Coordinate with #52 as we need to write a test for `plugin/index.js`, to avoid duplicated work :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by evgimov** [comment]
Can I do it?

**Comment by gr2m** [comment]
Hey Evghenii, this is quite a complex task, have you worked with automated testing and code coverage before? It’s not a good task to learn these things. Maybe try to go trough these steps and increase the code coverage and see if you feel comfortable doing it?

**Comment by evgimov** [comment]
I didn't worked before with it. Maybe you have another task for me?

2016-10-04 20:38 GMT-07:00 Gregor Martynus <notifications@github.com>:

**Comment by evgimov** [comment]
I haven't worked with automated testing. Yes, I will try. Maybe do you have
another task for me?

2016-10-04 20:38 GMT-07:00 Gregor Martynus notifications@github.com:

**Comment by gr2m** [comment]
Not right now, I’m sorry! But you can watch this repository to be notified of new issues. Great resources are http://www.firsttimersonly.com/ and http://yourfirstpr.github.io/, and look for issues with the [hacktoberfest label](https://github.com/search?utf8=%E2%9C%93&q=label%3Ahacktoberfest+is%3Aissue+is%3Aopen&type=Issues&ref=searchresults). Good luck!

**Comment by evgimov** [comment]
Thank you, have a good day!

2016-10-04 23:17 GMT-07:00 Gregor Martynus notifications@github.com:

**Comment by guntbert** [comment]
Hi, there seems to be a typo: "reserved until May 2016"?

**Comment by gr2m** [comment]
@guntbert thanks, removed it :)

**Comment by karanjthakkar** [comment]
@gr2m I'd like to pick this up if its still unclaimed :)

**Comment by nachiketdhamankar** [comment]
I'd like to give it a try if its open. It would be nice to try it as a first timer :)

**Comment by varjmes** [comment]
This appears to be unclaimed and @karanjthakkar came first. So, good luck Karan!

**Comment by varjmes** [comment]
@karanjthakkar I gave you write access to this repo so you can assign yourself :)

**Comment by karanjthakkar** [comment]
Thanks @Charlotteis! I'll send a PR in some time :)

**Comment by karanjthakkar** [comment]
I just realised that I'll be on vacation until mid next week, so someone else can pick this issue :)

**Comment by distalx** [comment]
I would like to give it a shot! :)

**Comment by nachiketdhamankar** [comment]
yay! I get to try it now right? :)

**Comment by gr2m** [comment]
@nachiketdhamankar do you know Node.js, testing, code coverage? It’s not a good issue for beginners, I just want to be sure you know what you commit to :)

**Comment by guiferpa** [comment]
Can I do it? 🛩

**Comment by gr2m** [comment]
do you two want to work on it together? @gpaixao you seem more experienced, would you be okay with taking some extra time and explaining how you will approach it first and why, and then do the implementation? I’ll be here of course to help answer questions as well.

@nachiketdhamankar would that work for you?

**Comment by nachiketdhamankar** [comment]
@gr2m That would be really nice :D

**Comment by guiferpa** [comment]
@gr2m ok, good idea. 

I've a question... The coverage in all modules of hoodiehq ? I'm reading here and don't know right where will do the coverage.

One more question :smiley: ... How will do the dynamics between me and @nachiketdhamankar

**Ps: I want catch this issue**

**Comment by gr2m** [comment]
@gpaixao the coverage is just for this repository: https://github.com/hoodiehq/hoodie-account-server. You can set it up and then run 

```
./node_modules/.bin/nyc report --reporter=lcov
```

This will create / update the `coverage` folder in the repository (it is ignored by git). Now open open coverage/lcov-report/index.html in your browser to see which lines are not yet covered by tests, then write tests until they are all covered

**Comment by guiferpa** [comment]
@gr2m tks. How do i get this issue for me? I've that set something?

**Comment by gr2m** [comment]
@gpaixao I’ve invited you to this repo, you can accept the invitation at https://github.com/hoodiehq/camp/invitations. Once accepted, you can assign yourself and start checking off the checkboxes above

**Comment by guiferpa** [comment]
@gr2m I'm studying the project, I like the issue 😆

**Comment by nachiketdhamankar** [comment]
@gr2m Can you add me too? I can just follow @gpaixao and try to understand if thats ok? :)

**Comment by guiferpa** [comment]
Don't need @nachiketdhamankar, I go create tests. Only write about that to doing!

**Comment by gr2m** [comment]
@nachiketdhamankar I’ve invited you to the repository, you can co-assign yourself once you accepted the invitation at https://github.com/hoodiehq/camp/invitations.

Good luck you two :)

**Comment by nachiketdhamankar** [comment]
@gpaixao I'm sorry I didn't get you ☺️

**Comment by nachiketdhamankar** [comment]
@gpaixao Is there any way I can contact you? :)

**Comment by guiferpa** [comment]
@nachiketdhamankar  yes, my e-mail: guilhermee.paixaoo@gmail.com .

**Comment by gr2m** [comment]
@gpaixao did you mean to close this issue? Current coverage is at 93%, still work to be done :)

**Comment by guiferpa** [comment]
Sorry sorry, I'm confounds. Sorry again. :/

**Comment by gr2m** [comment]
no problem :)

**Comment by gr2m** [comment]
hey @gpaixao @nachiketdhamankar are you still looking into this issue?

**Comment by guiferpa** [comment]
I have a problem in my work. I am out of time. :worried:

**Comment by gr2m** [comment]
no worries at all, all the best for your work 👍 

Anyone else want to give this a try?

**Comment by danieltotherescue** [comment]
Desireedesario and I (danieltotherescue) would like to work on this.

**Comment by LowProfileDog** [comment]
The issue is all yours :) I’ve invited you both to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

**Comment by gr2m** [comment]
try this for debugging coverage:

```
./node_modules/.bin/nyc report --reporter lcov
```

And then open `coverage/lcov-report/index.html` in your browser of choice

**Comment by gr2m** [comment]
all done via https://github.com/hoodiehq/hoodie-account-server/issues/226 thanks everyone!
