### ISSUE TITLE
🤐🔒 (ssh!) Write Blog Post announcing something very exciting

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#55]
![shh](https://media.giphy.com/media/yow6i0Zmp7G24/giphy.gif)
### 🤔 What you will need to know

You do _not_ need to know any coding, git or GitHub. Google Docs is perfectly fine for editing, we can take it from there :)
You should have experience with writing and agree that stickers are just the best thing ever. Review [our blog](http://hood.ie/blog/) to get an idea of what we are looking for, and have a look at our [blog process](https://github.com/hoodiehq/camp/wiki/Blog-Process).
### About unixstickers and their donation system
- donation system http://www.unixstickers.com/blog/unixstickers-new-donation-system-open-letter
- 😮 buy stickers on their terminal! https://www.unixstickers.com/terminal
- partnership with Sticker Mule http://www.unixstickers.com/blog/unixstickers-announces-partnership-with-sticker-mule

More from Agnese from unixstickers:

> Besides, a few more info: we’re up and running since 2010, we began small but we’re now the main e-commerce based on FOSS swag (and not only on that). Our HQ is in Italy (Bologna) but we ship worldwide and are mostly known abroad, especially in the US. 
> 
> The reason why we decided to donate back to our community is actually simple. As stated in the donation program post, our business wouldn’t exist without the FOSS projects and the communities around them, thus we felt both the need to support them and at the same time to be an active part of their communities.
### :dart: The goal

Two things we have _not_ yet announced (so keep it between us :)) but want to do so in form of a blog post:
1. We have a [Sticker Shop](https://www.stickermule.com/user/1070779325/stickers)
2. [Unixstickers’ October Campaign](http://www.unixstickers.com/donations/2016/10) is for Hoodie \o/

I know it’s very short term :( but we want to publish a blog post on Monday if possible
### 💭 Some thoughts / brainstorming
- At Hoodie we are very proud of the brand we are building, and [our animals and their stories](http://hood.ie/animals/) play an integral role.
- As an independent Open Source project, being fun is key to win and retain contributors, and stickers are a great way promote our brand. People put them on their laptops, other people see them, ask about them, a conversation starts and the awarness of Hoodie spreads :) Besides they are just cute and a great way for us to say thank you and to share with others. 
- 50% of the revenue goas towards our goal to hire a community manager, see https://twitter.com/hoodiehq/status/744915237854416896
- It would be nice to talk to someone at Unix Stickers (or collaborate on this blog post) to get their perspectives on stickers and the motivation behind their monthly donation campaigns
- I wonder if we can find out where this whole sticker hysteria came from in Open Source? That would be a nice story to tell :)
### :clipboard: Step by Step
- [ ] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Once claimed we add you as contributor to this repository. Please add a link to your blog or articles that you wrote before :)
- [ ] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [ ] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [ ] 🔄 **replace** the `up for grabs` label with `in progress`.
- [ ] 📝 **create a Google Doc** and tell us the link at which we can comment on it
- [ ] **Write** a first draft of the blog post.
- [ ] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#THIS_ISSUE_NUMBER` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [ ] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
- [ ] Before publishing, add a `Stickers!` Section to [Hoodie’s README file](https://github.com/hoodiehq/hoodie#readme) with the image below linked to our shop :)
    [![stickers](https://dl.dropboxusercontent.com/u/732913/tmp/stickers.png)](https://www.stickermule.com/user/1070779325/stickers)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by mathesond2** [comment]
I'll take it!! May I get assigned as a contributor?

**Comment by LowProfileDog** [comment]
Welcome David, I’ve invited you to the Camp repository! You can accept yourself our invitation at https://github.com/hoodiehq/camp/invitations. Once accepted you can assign yourself and start a draft.

If you don’t mind, we would like to invite others to help collaborating / editing the blog post.

Do you have a blog or can link to articles that you wrote before?

**Comment by mathesond2** [comment]
@LowProfileDog sure thing! Here's a [link](https://github.com/mathesond2/portfolio/blob/063c268426e5236afc7d581ec9185844a1ccb720/_posts/2015-03-06-hometrackr-ui.markdown) to a few posts I have; I'm currently revamping my portfolio site, so had to dig through my git history..also, theres several more articles in the `_posts` folder. And of course, collaborators sound fine my way. 😀

**Comment by gr2m** [comment]
Great thanks, welcome to Hoodie :) Can you assign yourself and start working off the list above? It would be great if you could create a google doc with a link at which people can add comments. If people want to collaborate you can invite them per email.

**Comment by igotpassion** [comment]
Happy to help out! You can find my stuff here (robertgibb.me, meaningfulcafe.com, maxcdn.com/blog)

**Comment by gr2m** [comment]
Robert created a Google Doc here to collaborate: https://docs.google.com/document/d/1p0Xwib60sgI-FCE47_9Uc_YMc0eSfSDiyWhEInktLUw/edit

**Comment by igotpassion** [comment]
@mathesond2 Want to start a draft? I would say we should create an outline first but @gr2m already took care of that. The only thing that isn't in the outline is a story arc, but I know Gregor mentioned the idea of covering how stickers first made their appearance in the open source community. There's probably some cool history there that we can cover. 

Let me know if you have any questions. Because we want to publish Monday I'm going to tie everything up tonight (traveling during the day).

**Comment by mathesond2** [comment]
Hey @igotpassion sure thing! I'm currently finishing a lecture for work tomorrow so I'll probably be able to start in 3 hours or so; my apologies for the delay. 😇

**Comment by igotpassion** [comment]
@mathewond2 Make sure to tag @gr2m and @jdorfman before you start because I think they are working on it too. I'm running on fumes but I'll be able to edit it tomorrow AM before I start the weekday grind.

**Comment by igotpassion** [comment]
@mathesond2 I meant 😊

**Comment by gr2m** [comment]
@jdorfman and I are not working on it, but I’m here to answer any questions you might have. I left a few comments on the post

**Comment by igotpassion** [comment]
Thanks for clarifying.

**Comment by mathesond2** [comment]
I'm on it!

**Comment by mathesond2** [comment]
would love some feedback when y'all have a moment..I think it may be a bit too terse?

**Comment by igotpassion** [comment]
Hey @mathesond2. Thanks for helping out. I've made some revisions and additions here: https://docs.google.com/document/d/1jQWtiBtIMkTUf21Dmoifq13k1CdZ524jYedVHPfsWIg/edit?usp=sharing After you and @gr2m respond with your comments I'll go ahead and clean it up for publishing. @gr2m There will be some parts where you need to add emojis/icons when preparing to publish 👍

**Comment by mathesond2** [comment]
@igotpassion looks good!

**Comment by jennwrites** [comment]
Just finished reviewing and this is a good start @mathesond2. ☺️

Before moving forward I would review past blog posts on Hoodie’s [blog](http://hood.ie/blog/) to get a feel for the style of the posts there. Also check out the [philosophy](http://hood.ie/about/) and [code of conduct](http://hood.ie/code-of-conduct/) pages for an understanding on how we communicate. 

There seems to be an emphasis on branding, which I see was part of the direction and that’s a miscommunication. We need to instead clearly communicate our emphasis on creating great community and making it fun to participate (@gr2m is a great resource for both) – the animals are a manifestation of that. 🐶 

Let me know if you have any questions about my feedback.

**Comment by mathesond2** [comment]
@renrutnnej sounds good to me...have you had a chance to review @igotpassion's draft as well? 

https://docs.google.com/document/d/1jQWtiBtIMkTUf21Dmoifq13k1CdZ524jYedVHPfsWIg/edit?usp=sharing

**Comment by jennwrites** [comment]
@mathesond2 The linked Google doc is the only one I reviewed. Is there another one?

**Comment by gr2m** [comment]
it’s the same, Jenn already left a ton of comments in that google doc :)

**Comment by skeskali** [comment]
This looks good to me!

**Comment by jennwrites** [comment]
I thought of something else that needs mentioning once we decide to move forward with the sticker shop. We can't forget to give credit to the artist who created the sticker artwork, illustrator [Carolina Buzio](https://twitter.com/CarolinaBuzio). ✨ Thanks!

**Comment by mathesond2** [comment]
will do! :)

**Comment by gr2m** [comment]
thanks all for your help, I’m going to close this issue for now as we’ve put it on hold :(

**Comment by mathesond2** [comment]
sounds good
