### ISSUE TITLE
[Hoodie Account Server API] api.sessions.remove -> rejects if options is not passed 

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#58]
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

You should have worked with JavaScript, Node.js and Testing. If you haven’t yet, we recommend the [JavaScript Track on exercism.io](http://exercism.io/languages/javascript)
### 🐞 The Bug

``` js
var AccountApi = require('@hoodie/account-server-api')
var PouchDB = require('pouchdb-core').plugin(require('pouchdb-adapter-memory')).plugin(require('pouchdb-mapreduce'))

var api = new AccountApi({
  PouchDB: PouchDB,
  secret: 'secret123'
})

api.sessions.remove('sessionid').catch(function (error) {
  // { [not_found: missing]
  //   status: 404,
  //   name: 'not_found',
  //   message: 'missing',
  //   error: true,
  //   reason: 'missing' }
}) 
```

We prepared a test to reproduce this issue at [test/unit/sessions/remove-test.js#L25](https://github.com/hoodiehq/hoodie-account-server-api/blob/4d49fb56eb887df38e3b40a658daf8f43368eaa4/test/unit/sessions/remove-test.js#L25-L26)
### :dart: The goal

Make the test pass :) 
### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it during the event.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 🗜 [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server-api#testing)
- [x] Remove the comment and the `, {skip: true}` at  [test/unit/sessions/remove-test.js#L25](https://github.com/hoodiehq/hoodie-account-server-api/blob/4d49fb56eb887df38e3b40a658daf8f43368eaa4/test/unit/sessions/remove-test.js#L25-L26). Tests should fail now. 
- [x] **Commit the change** with `test: sessions.remove('sessionid')` and push it either to your fork or push your new branch.
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#58` in the description.  
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by gr2m** [comment]
Hey @distalx this issue is reserved for [the event tomorrow](https://www.meetup.com/la-fullstack/events/234637657/), I’m sorry. That’s why the banner is there on top of the issue :)

**Comment by distalx** [comment]
My apologies.

**Comment by gr2m** [comment]
no worries :) it's free now, if you’d like to give it a go?

**Comment by Taekyoon** [comment]
Greg, can I deal with this?
If I can, I will do that!

**Comment by LowProfileDog** [comment]
@Taekyoon is working on this with @jimthoburn :) good luck!
