### ISSUE TITLE
[Hoodie Account Server API] friendly error message for accounts.add({username: ''})

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#60]
[![This issue is reserved for Fullstack ⚡️ Open Source | Hacktober Edition](https://dl.dropboxusercontent.com/u/732913/fullstack-hacktoberfest-banner.png)](https://www.meetup.com/la-fullstack/events/234637657/)
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

You should have worked with JavaScript, Node.js and Testing. If you haven’t yet, we recommend the [JavaScript Track on exercism.io](http://exercism.io/languages/javascript)
### 🐞 The Bug

``` js
var AccountApi = require('@hoodie/account-server-api')

var AccountApi = require('.')
var PouchDB = require('pouchdb-core').plugin(require('pouchdb-adapter-memory')).plugin(require('pouchdb-mapreduce'))

var api = new AccountApi({
  PouchDB: PouchDB,
  secret: 'secret123'
})

api.accounts.add({}).catch(function (error) {
  // forbidden: doc.name is required
}) 
```

We prepared a test to reproduce this issue at [test/unit/accounts/add-test.js#L6](https://github.com/hoodiehq/hoodie-account-server-api/blob/master/test/unit/accounts/add-test.js#L6)
### :dart: The goal

Make the test pass :) 
### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🙋 **Claim this issue**: @simonyangme (Note: [Fullstack LA Hacktoberfest Edition attendees only](https://www.meetup.com/la-fullstack/events/234637657/)) Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it during the event.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 🗜 [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server-api#testing)
- [x] Remove the `, {skip: true}` at  [test/unit/accounts/add-test.js#L6](https://github.com/hoodiehq/hoodie-account-server-api/blob/4d49fb56eb887df38e3b40a658daf8f43368eaa4/test/unit/accounts/add-test.js#L6). Tests should fail now. 
- [x] **Commit the change** with `test: accounts.add({})` and push it either to your fork or push the new branch.
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#60` in the description.  
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by simonyangme** [comment]
Claiming

**Comment by LowProfileDog** [comment]
The issue is all yours :) I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

**Comment by simonyangme** [comment]
@LowProfileDog please review :smile_cat:
