### ISSUE TITLE
[hoodie-account-server] save createdAt & signedUpAt timestamps

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#61]
[![This issue is reserved for Fullstack ⚡️ Open Source | Hacktober Edition](https://dl.dropboxusercontent.com/u/732913/fullstack-hacktoberfest-banner.png)](https://www.meetup.com/la-fullstack/events/234637657/)
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

You should have worked with JavaScript, Node.js and Testing. This is a rather advanced issue, you will need to write tests yourself and then resolve the issue. If you haven’t done that before, better look for another issue :) 

Some knowledge about [Hapi](http://hapijs.com/) will help but you can figure it out if you know the things above :)
### 🐞 The Bug

A special aspect of Hoodie is that it works offline. A side effect of that is that you can use an application even without signing up. To see an example of that, open https://minutes.io/welcome and click on "Try it now".

What we want to do now is to save the timestamp the user opens the app for the first time, as well as the timestamp the user eventually signs up (creates account on the server using `hoodie.account.signUp()`

Right now, neither of these timestamps are stored.
### :dart: The goal

The `PUT /sessions/account` request that `hoodie.account.signUp()` sends will include a `createdAt` property besides username, password and id. If it’s not, set it to the current time (`new Date().toISOString()`).

Additionally, add the property `signedUpAt` and set it to the current time.

That way we can later do analysis on our app’s users in terms of how long it took them to sign up after they started using the app :)
### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🙋 **Claim this issue**: (Note: [Fullstack LA Hacktoberfest Edition attendees only](https://www.meetup.com/la-fullstack/events/234637657/)) Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it during the event.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 🗜 [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server/blob/master/tests/README.md#testing)
- [x] Add an integration test or adapt an existing test at [tests/integration/routes/account/put-account-test.js](https://github.com/hoodiehq/hoodie-account-server/blob/master/tests/integration/routes/account/put-account-test.js)
- [x] **Commit the change** with `test(routes): signup timestamps` and push it either to your fork or push your new branch. Your tests should fail now
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#61` in the description.  
- [x] Implement the feature as described in "The goal" above. Commit often, don’t worry about messages, push your work-in-progress to your pull request, that helps with the discussion :) Reach out for help if you have any questions
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by nhatbui** [comment]
@xuhdev and I are tackling this! 🙌

**Comment by hextor** [comment]
I would like to attempt this.

**Comment by gr2m** [comment]
@Ghalander Simon is already working on it, sorry! But check out the other issues. Most of the available ones are reserved for today’s event here at Fullstack LA, but we will free them up tonight
