### ISSUE TITLE
[hoodie-account-server] GET /accounts Add test for 401 "Session invalid"

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#62]
[![This issue is reserved for Fullstack ⚡️ Open Source | Hacktober Edition](https://dl.dropboxusercontent.com/u/732913/fullstack-hacktoberfest-banner.png)](https://www.meetup.com/la-fullstack/events/234637657/)
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

You should have worked with JavaScript, Node.js and Testing. This is a rather advanced issue, you will need to write tests yourself and then resolve the issue. If you haven’t done that before, better look for another issue :) 

Some knowledge about [Hapi](http://hapijs.com/) will help but you can figure it out if you know the things above :)
### 🐞 The Bug

Requests like `GET /accounts` require a valid session. The server validates the session by parsing the `authorization` request header. 

As defined in the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/admins/user-account-collection/list-all), the server should respond with `401 Unauthorized – Authorization header missing` instead of `403`.
### :dart: The goal

As defined in the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/account/fetch), the server should respond with `401 Unauthorized – Session invalid`. It probably does that already but we can’t be sure unless we have a test for it :)
### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🙋 **Claim this issue**: @simonyangme (Note: [Fullstack LA Hacktoberfest Edition attendees only](https://www.meetup.com/la-fullstack/events/234637657/)) Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it during the event.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🏷  **add** the label `in progress`.
- [x] 🗜 [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server/blob/master/tests/README.md#testing)
- [x] Create the test in [tests/integration/routes/accounts/get-accounts-test.js](https://github.com/hoodiehq/hoodie-account-server/blob/3d54bb0b87afc87e0897883e1c0837b44324105b/tests/integration/routes/accounts/get-accounts-test.js#L54-L56)
- [x] **Commit the change** with `test(routes): GET /accounts with invalid session` and push it either to your fork or push your new branch. Your tests should fail now
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#62` in the description.  
- [x] If the test passes, all good 👍 If the server does not respond as expected, figure out why and fix it 👍 
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by simonyangme** [comment]
@LowProfileDog requesting review :smile_cat:
