### ISSUE TITLE
[hoodie-account-server] Add test for GET /accounts?include=foobar

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#63]
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

You should have worked with JavaScript, Node.js and Testing. This is a rather advanced issue, you will need to write tests yourself and then resolve the issue. If you haven’t done that before, better look for another issue :) 

Some knowledge about [Hapi](http://hapijs.com/) will help but you can figure it out if you know the things above :)

The `/?include` query parameter is part of the [JSON API specification](http://jsonapi.org/format/#fetching-includes). The spec says

> If an endpoint does not support the include parameter, it MUST respond with 400 Bad Request to any requests that include it.

We don’t test for this specific case yet. But you can look how the test looks like for [`POST /accounts?include=foobar`](https://github.com/hoodiehq/hoodie-account-server/blob/742d3983982dd4e0027731a65278664151fde273/tests/integration/routes/accounts/post-accounts-test.js#L132-L142), it will probably be pretty similar
### 🎯 The goal

Create an integration test for `GET /accounts?include=foobar` and make it pass :)
### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it during the event.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🏷  **add** the label `in progress`.
- [x] 🗜 [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Create the test in [tests/integration/routes/accounts/get-accounts-test.js](https://github.com/hoodiehq/hoodie-account-server/blob/0d3bc875a51310befec447d2944385d5152eb380/tests/integration/routes/accounts/get-accounts-test.js#L158-L160)
- [x] **Commit the change** with `test(routes): GET /accounts?include=foobar` and push it either to your fork or push your new branch. Your tests should fail now
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#63` in the description.  
- [x] If the test passes, all good 👍 If the server does not respond as expected, figure out why and fix it 👍 
- [ ] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by sigorilla** [comment]
Hi! Can I work on this issue?

**Comment by sigorilla** [comment]
Oh, sorry. I was inattentive and did not notice a mark about participation. Although if you're still interested, here is [my code](https://github.com/hoodiehq/hoodie-account-server/compare/master...sigorilla:get-accounts-test?expand=1) for this issue. And I'm ready to fix other issues with tests :smile:

**Comment by gr2m** [comment]
Code looks good, thanks @sigorilla! I’d like to wait if someone from the event would like to take it on, and they could even use your code if they can’t figure it out by themselves as a help. They are many beginners here today so this is a great help :) We will create more issues in future, and issues that are not done today will be free to take for everyone tomorrow

**Comment by gr2m** [comment]
Hey Igor, the issue is available for everyone now, do you want to start a PR? I’ve invited you to the repository: https://github.com/hoodiehq/camp/invitations Once accepted you can assign yourself and start checking off the the steps above :)

**Comment by sigorilla** [comment]
Yep! Good! I'm ready for PR
