### ISSUE TITLE
[hoodie-account-server] Add test for PATCH /accounts/{id} if user is not an admin

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#68]
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

You should have worked with JavaScript, Node.js and Testing. This is a rather advanced issue, you will need to write tests yourself and then resolve the issue. If you haven’t done that before, better look for another issue :) 

Some knowledge about [Hapi](http://hapijs.com/) will help but you can figure it out if you know the things above :)

In order to load a account via `GET /accounts/{id}`, the admin must be authenticated with a valid session id. If they are not, the server must respond with `401 invalid session` as [per spec](http://docs.accountjsonapi.apiary.io/#reference/admins/user-account/update). That includes the case where the session id is valid, but the user is not an admin

It probably does that already but we can’t be 100% sure unless we actually test it :)
### 🎯 The goal

Create an integration test for `PATCH /accounts/{id}` with a valid session that belongs to a user account, not an admin account :)
### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it during the event.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🏷  **add the label** `in progress`.
- [x] 🗜 [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Create the test in [tests/integration/routes/accounts/patch-accounts-test.js](https://github.com/hoodiehq/hoodie-account-server/blob/5932559e97560912d8f59465b58dbcc7716dc2ea/tests/integration/routes/accounts/patch-accounts-test.js#L107-L109).
- [x] **Commit the change** with `test(routes): PATCH /accounts/{id} with user session` and push it either to your fork or push your new branch. Your tests should fail now
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#68` in the description.  
- [x] If the test passes, all good 👍 If the server does not respond as expected, figure out why and fix it 👍 
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by codingCookie** [comment]
Hi, can i try this one?

**Comment by LowProfileDog** [comment]
The issue is all yours :) I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

**Comment by codingCookie** [comment]
@LowProfileDog I think I'll have to give up on that issue :( 
thought i would get it, but i think it is too much at the moment :/ sorry

**Comment by gr2m** [comment]
No problem at all :) You are always welcome to try another one

**Comment by sharynneazhar** [comment]
if this is open, I would like to try working on it :)

**Comment by gr2m** [comment]
All yours @sharynneazhar :) I’ve invited you to this repository: https://github.com/hoodiehq/camp/invitations once accepted, assign yourself to this issue and start working off the list above :) Enjoy! And please let us know if you have any questions.

**Comment by sharynneazhar** [comment]
The link above said to add the test to the delete-account-test file, but I'm assuming that was a copy pasta error? 😅 It should be in patch-account-test, correct?

**Comment by gr2m** [comment]
> The link above said to add the test to the delete-account-test file, but I'm assuming that was a copy pasta error? 😅 It should be in patch-account-test, correct? 

Absolutely :) Oooopsie

**Comment by gr2m** [comment]
hey @sharynneazhar how are things going? Anything we can help with?

**Comment by sharynneazhar** [comment]
ah I apologize for taking so long. Got caught up with midterms and group projects. I was planning on making the PR this weekend :)

**Comment by gr2m** [comment]
no problem, let us know if we can help with anything :)

**Comment by sharynneazhar** [comment]
@gr2m I can't push my branch up. Can you add me as a collaborator? If not, I can make a fork and make a pull request that way.

**Comment by gr2m** [comment]
@sharynneazhar invited you :) welcome to Hoodie

**Comment by sharynneazhar** [comment]
@gr2m Thanks! The PR is ready for review :) Any feedback appreciated!

I wasn't too sure about the authorization header, so let me know if it's not doing what it's supposed to. :)

**Comment by gr2m** [comment]
That was great :) let me know if you’d like to work on another issue, maybe something more challenging? Happy to help find something interesting

**Comment by sharynneazhar** [comment]
@gr2m Yeah, for sure! Just ping me what you have :)

**Comment by gr2m** [comment]
would you like working on increasing test coverage for https://github.com/hoodiehq/hoodie-account-server-api? It’s pretty poor right now.

You have to run `npm test` first, it will also give you a coverage summary. Then run

```
./node_modules/.bin/nyc report --reporter=lc
```

Which creates a local HTML coverage report, which you can open with `open coverage/lcov-report/index.html` which should open the report in your default browser. You can then browse trough the files and look for the lines with red background, these are the ones which are not yet covered, and we which we have to write tests for to change that

Let me know if you have any questions :)
