### ISSUE TITLE
[hoodie-account-server] Add test for PATCH /accounts/{id} if account not found

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#69]
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

You should have worked with JavaScript, Node.js and Testing. This is a rather advanced issue, you will need to write tests yourself and then resolve the issue. If you haven’t done that before, better look for another issue :) 

Some knowledge about [Hapi](http://hapijs.com/) and [JSON API](http://jsonapi.org/) will help but you can figure it out if you know the things above :)

If an admin tries to update an account via `PATCH /accounts/123` but the account with id `123` no longer exist, the server should respond with `404 not found`.

It probably does that already but we can’t be 100% sure unless we actually test it :) The test will probably look similar to the one we created for [`GET /accounts/123`](https://github.com/hoodiehq/hoodie-account-server/blob/b83442f3c6f0a8055eac09b845e65b345494d9e3/tests/integration/routes/accounts/get-accounts-test.js#L218-L238)
### 🎯 The goal

Create an integration test for `GET /accounts/{id}` if account not found :)
### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it during the event.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🏷  **add the label** `in progress`.
- [x] 🗜 [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Create the test in [tests/integration/routes/accounts/patch-accounts-test.js](https://github.com/hoodiehq/hoodie-account-server/blob/b83442f3c6f0a8055eac09b845e65b345494d9e3/tests/integration/routes/accounts/patch-accounts-test.js#L99-L101).
- [x] **Commit the change** with `test(routes): PATCH /accounts/{id} if account not found` and push it either to your fork or push your new branch. Your tests should fail now
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#69` in the description.  
- [x] If the test passes, all good 👍 If the server does not respond as expected, figure out why and fix it 👍 
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by minrwhite** [comment]
Can I grab this one?

**Comment by LowProfileDog** [comment]
The issue is all yours :) I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

**Comment by minrwhite** [comment]
All done; ready for review.
