### ISSUE TITLE
[hoodie-account-server] PATCH /accounts/{id} should respond with 204 unless ?include=profile query set

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#70]
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

You should have worked with JavaScript, Node.js and Testing. This is a rather advanced issue, you will need to write tests yourself and then resolve the issue. If you haven’t done that before, better look for another issue :) 

Some knowledge about [Hapi](http://hapijs.com/) and [JSON API](http://jsonapi.org/) will help but you can figure it out if you know the things above :)

`PATCH /accounts/123` should respond with a `204 no content` and an empty body unless `?include=profile` is set. That means that the response body should be empty. See [the spec](http://docs.accountjsonapi.apiary.io/#reference/admins/user-account/update)

The server is currently not behaving that way, see [tests/integration/routes/accounts/patch-accounts-test.js](https://github.com/hoodiehq/hoodie-account-server/blob/b83442f3c6f0a8055eac09b845e65b345494d9e3/tests/integration/routes/accounts/patch-accounts-test.js#L107-L126). 
### 🎯 The goal

Update the existing test for password change and while at it, create the one for username change :) `response.statusCode` should be `204` instead of `201` and `response.result` should be `null`, for both tests.
### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it during the event.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🏷  **add the label** `in progress`.
- [x] 🗜 [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Update the test in [changing password test](https://github.com/hoodiehq/hoodie-account-server/blob/b83442f3c6f0a8055eac09b845e65b345494d9e3/tests/integration/routes/accounts/patch-accounts-test.js#L107-L122).
- [x] **Commit the change** with `test(routes): PATCH /accounts/{id} password update response 204` and push it either to your fork or push your new branch. Your tests should fail now
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#70` in the description.  
- [x] Implement the necessary changes in the code to make the test pass. Make sure that if `?include=profile` is passed, the response should remain as is, with `201` status code and the account in the response body.
- [x] Add the test for for changing username and make it pass
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by Taekyoon** [comment]
Hey Greg! I'll handle with this!

**Comment by gr2m** [comment]
👍 thanks

**Comment by Taekyoon** [comment]
Greg! I can't try this issue right now. It's quite hard to deal with npm test. If possible, can u recommend references to learn some information to study this test?

**Comment by gr2m** [comment]
change [these lines](https://github.com/hoodiehq/hoodie-account-server/blob/b83442f3c6f0a8055eac09b845e65b345494d9e3/tests/integration/routes/accounts/patch-accounts-test.js#L118-L119) to

```
t.is(response.statusCode, 204, 'returns 204 status')
t.is(response.result, null, 'returns no content')
```

Commit the change with `test(routes): PATCH /accounts/{id} password update response 204`, then start a pull request, we can discuss there, ok?

**Comment by Taekyoon** [comment]
Thanks! I'll do that first!
