### ISSUE TITLE
[hoodie-account-server] Add test for DELETE /accounts/{id} with invalid session

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#74]
### 🤔 What you will need to know

You should have worked with JavaScript, Node.js and Testing. This is a rather advanced issue, you will need to write tests yourself and then resolve the issue. If you haven’t done that before, better look for another issue :) 

Some knowledge about [Hapi](http://hapijs.com/) or [JSON API](http://jsonapi.org/) will help but you can figure it out if you know the things above :)

In order to delete an account via `DELETE /accounts/{id}`, the admin must be authenticated with a valid session id. If they are not, the server must respond with `401 invalid session` as [per spec](http://docs.accountjsonapi.apiary.io/#reference/admins/user-account/delete)

It probably does that already but we can’t be 100% sure unless we actually test it :)
### 🎯 The goal

Create an integration test for `DELETE /accounts/{id}` with an invalid session and make it pass :)
### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it during the event.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🏷  **add the label** `in progress`.
- [x] 🗜 [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Create the test in [tests/integration/routes/accounts/delete-accounts-test.js](https://github.com/hoodiehq/hoodie-account-server/blob/e3b60d184b3668d676cffee7f0b82b79ad37ce21/tests/integration/routes/accounts/delete-accounts-test.js#L89-L91).
- [x] **Commit the change** with `test(routes): DELETE /accounts/{id} with invalid session` and push it either to your fork or push your new branch. Your tests should fail now
- [ ] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#74` in the description.  
- [x] If the test passes, all good 👍 If the server does not respond as expected, figure out why and fix it 👍 
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by jaimemendozadev** [comment]
I'll claim it.

**Comment by LowProfileDog** [comment]
The issue is all yours :) I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

**Comment by gr2m** [comment]
@jaimemendozadev are you still working on this PR: https://github.com/hoodiehq/hoodie-account-server/pull/206? Or shall we let someone else give it a try?

**Comment by jaimemendozadev** [comment]
Hey @gr2m! No, I'm not working on it. By all means let someone else give it a try! 😄

**Comment by gr2m** [comment]
Thanks Jaime, I’m opening this up for  [Write/Speak/Code Open Source Hours](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/) :)

**Comment by Taekyoon** [comment]
Hey @gr2m If I fail to take issue #51 , can I try this issue?

**Comment by gr2m** [comment]
@Taekyoon let me know if you need any help :)

**Comment by Taekyoon** [comment]
@gr2m I gotta some works from outside, so I'll push my updated project in this week!!
