### ISSUE TITLE
Hoodie default UI

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#8]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

JavaScript, Node.js. Maybe some [hapi](http://hapijs.com/) but shouldn’t be too much.
### ❓ The Motivation

Hoodie as a page that is displayed at `/hoodie`. It’s not very helpful at this page, but we’ll get there :) Here’s how it currently looks like: https://tracker.hood.ie/hoodie/

The same html page is shown at the `/` root path if your app has no `public/` folder. But we want to differentiate between these two cases, as they have two different use cases.
### :dart: The goal

If your app has no `public/` folder, the Hoodie Server should show a fallback UI. When opening `/hoodie` in your app, the server should show the contents of [hoodie/public](https://github.com/hoodiehq/hoodie/tree/master/public).
### :clipboard: Step by Step
- [x] **claim this issue**: @distalx 
- [x] **[Setup the hoodie repository locally](https://github.com/hoodiehq/hoodie#testing)** and make sure that all tests pass
- [ ] **Implement the feature** :) The check if the app has a `public/` folder is currently implemented in [ hoodie/server/config/index.js ](https://github.com/hoodiehq/hoodie/blob/82897fd/server/config/index.js#L30-L36)
- [ ] **Commit** with `feat: Hoodie default UI`  
  Don’t worry about wording or amount of commits. We will clean up everything before we merge :) Also please commit work in progress things if you get stuck, we can work on it together in the PR, and others can take over.
- [ ] **Start a Pull Request**. Mention `closes hoodiehq/camp#8` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [ ] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by ArcadiusK** [comment]
I have some ideas about improving the page.

**Comment by gr2m** [comment]
I’ve merged your PR it was great, thanks! But it’s not quite what this issue is about. This issue is about showing something different at `/` and `/hoodie` when your app has now `/public` folder.

The page you edited is the "fallback UI". I would put that into a new folder in the `hoodie` repository, and call it `fallback-ui`. The `hoodie/index.html` file we can just change to some dummy content for now like `Hello from Hoodie Server!`. 

When I open http://localhost:8080/hoodie in my app, I should see `Hello from Hoodie Server!`. When I open http://localhost:8080 and my app has no own `public/` folder, I should see `fallback-ui/index.html` from the `hoodie` repo, does that make sense?

**Comment by distalx** [comment]
Has this been completed yet? Otherwise,  I would like to give it a shot!

**Comment by gr2m** [comment]
Oh this is actually a duplicate for https://github.com/hoodiehq/camp/issues/20, and yes, it is up for grabs. @cheapwebmonkey expressed interest to work on the default UIs for `/hoodie`, `/hoodie/account` and `/hoodie/store`, so maybe we can collaborate? Feel free to start a pull request to create a base for discussion :)

**Comment by gr2m** [comment]
@distalx @ArcadiusK still interested in working on this?

**Comment by distalx** [comment]
haven't this already been addressed in https://github.com/hoodiehq/hoodie/pull/583 ?

**Comment by gr2m** [comment]
hoodiehq/hoodie#583 was about a fallback UI that is shown if your app has no public folder. It shown when you open the `/` path. This issue is about what we will show if you open the `/hoodie` path, every hoodie app will have that

**Comment by distalx** [comment]
My understanding was it's a duplicate issue so I closed my PR, Since @thepudding had already started working on this,  if it's okey with @thepudding - I'd be happy to help / coordinate with @thepudding. :) Thanks.

**Comment by thepudding** [comment]
Hi, hope I didn't step on any toes. I'd be happy to work with @distalx on this. 

Is the pull request I submitted on the right track? I think the static pages under `/hoodie` and `/fallback-ui` could be more helpfully written...

**Comment by shadeven** [comment]
Hi all, has this issue been completed yet? I would like to contribute if it is still open. Thanks.

**Comment by gr2m** [comment]
Hey thank you all for your work on this. I’m sorry that we couldn’t follow up in time :(

We have a clearer picture now on what the default Hoodie UI would look like. In a nutshell, if there is no `public` folder in a app, the `/` root path will redirect to `/hoodie` and at `/hoodie` we will show some relevant information like the current version of hoodie. And if no `public` folder is defined, we will show a note at `/hoodie` on how to create one or point to the right place in our docs.

Once we thought it through entirely we’ll create a new issue for it with better instructions. Would you like me to reach out to you again once it’s ready to be worked on?
