### ISSUE TITLE
📑🖋 Create LICENSE in pouchdb-users repository

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#80]
### 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 Read more about [First Timers Only](http://www.firsttimersonly.com/)
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process
### ❓ The Motivation

GitHub recently released a new feature which [shows the repository’s license on the overview page](https://github.com/blog/2252-license-now-displayed-on-repository-overview). While all of Hoodie’s repositories have a License ([Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0)), it is not displayed on the overview. The reason is that our `LICENSE` files are missing a few parts.
### :dart: The goal

The license should be displayed on [hoodiehq/pouchdb-users’s overview page](https://github.com/hoodiehq/pouchdb-users) like it is displayed on the [hoodiehq/hoodie repository](https://github.com/hoodiehq/hoodie)

<a href="https://github.com/hoodiehq/hoodie"><img width="981" alt="screen shot 2016-10-02 at 11 12 54" src="https://cloud.githubusercontent.com/assets/39992/19022632/4922944e-8891-11e6-9fa3-39929715053e.png"></a>
### :clipboard: Step by Step
- [x] 🙋 **Claim this issue**: Comment below. Note: this is a first-timers-only issue, reserved for people who did not yet contribute to an Open Source project other than their own. We will wait a bit to give more people a chance to claim it and then randomly assign it to one of the people who would like to try it. 
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 📝 **Create** [hoodiehq/pouchdb-users’s LICENSE file](https://github.com/hoodiehq/pouchdb-users/blob/master/LICENSE) with the content of [hoodiehq/hoodie’s LICENSE file](https://raw.githubusercontent.com/hoodiehq/hoodie/master/LICENSE).
- [x] 💾 **Commit** your changes with the message `chore(LICENSE): use standard Apache V2.0 text`
- [x] 🔀 **Start a Pull Request**. Set the title to `LICENSE: use standard Apache V2.0 text` and set description to `closes hoodiehq/camp#56. There are two ways how you can start a pull request:
  1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
  2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by n0rev** [comment]
I would like to claim this issue 😄

**Comment by leighphan** [comment]
Hey Erick! This specific issue is reserved for those who have not submitted a pull request before (see first-timers-only label) at our Hacktoberfest event today.

Please check out other issues not specified for first-timers-only. We'll also create more issues in the near future!

**Comment by nachiketdhamankar** [comment]
Hey! Can I try this?

**Comment by stain88** [comment]
Hey, is this issue still up for grabs?

**Comment by g-akash** [comment]
Hi, I want to work on this.

**Comment by Taekyoon** [comment]
Greg, can I try this again? I need to one more practice.

**Comment by gr2m** [comment]
sorry @Taekyoon, first-timers only :) I think you are doing great, try contribute something else

**Comment by iulyaav** [comment]
I would also like to try. :smile_cat:

**Comment by 7ictor** [comment]
I would like to claim this issue. 🖐

**Comment by eopuntia** [comment]
Could I please claim this issue?

**Comment by MarckK** [comment]
I'd like to claim this issue!

**Comment by reyesr3** [comment]
@justinjyoo and I are working on this.

**Comment by LowProfileDog** [comment]
I’ve invited you two to this repository, you can accept the invitation at https://github.com/hoodiehq/camp/invitations. Once accepted, you can assign yourself to this issue and work off the steps above :)

**Comment by Janatbek** [comment]
We'd like to pair on this issue.
@emilyyutschmidtling,

**Comment by LowProfileDog** [comment]
@janatbek it’s already taken, do you want to try https://github.com/hoodiehq/camp/issues/83 – it’s the same thing :)

**Comment by Dinika** [comment]
So, I'm guessing this issue has already been grabbed? If not, I'd love to claim it!

**Comment by Janatbek** [comment]
@gr2m I think we started working on it, but then we chose delete user npm test  issue. this issue was token by someone else.

**Comment by rohan097** [comment]
I would like to claim this issue, if it is still open.
