### ISSUE TITLE
📑🖋 Update LICENSE in hoodie-zuul-config repository

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#83]
### 🆕🐥☝ First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 Read more about [First Timers Only](http://www.firsttimersonly.com/)
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process
### ❓ The Motivation

GitHub recently released a new feature which [shows the repository’s license on the overview page](https://github.com/blog/2252-license-now-displayed-on-repository-overview). While all of Hoodie’s repositories have a License ([Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0)), it is not displayed on the overview. The reason is that our `LICENSE` files are missing a few parts.
### :dart: The goal

The license should be displayed on [hoodiehq/hoodie-zuul-config’s overview page](https://github.com/hoodiehq/hoodie-zuul-config) like it is displayed on the [hoodiehq/hoodie repository](https://github.com/hoodiehq/hoodie)

<a href="https://github.com/hoodiehq/hoodie"><img width="981" alt="screen shot 2016-10-02 at 11 12 54" src="https://cloud.githubusercontent.com/assets/39992/19022632/4922944e-8891-11e6-9fa3-39929715053e.png"></a>
### :clipboard: Step by Step
- [x] 🙋 **Claim this issue**: Comment below
  Please 🙏 only claim if you want to start working on it within a day.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 📝 **Update** [hoodiehq/hoodie-zuul-config’s LICENSE file](https://github.com/hoodiehq/hoodie-zuul-config/blob/master/LICENSE) with the content of [hoodiehq/hoodie’s LICENSE file](https://raw.githubusercontent.com/hoodiehq/hoodie/master/LICENSE).
- [x] 💾 **Commit** your changes with the message `chore(LICENSE): use standard Apache V2.0 text`
- [x] 🔀 **Start a Pull Request**. Set the title to `LICENSE: use standard Apache V2.0 text` and set description to `closes hoodiehq/camp#56. There are two ways how you can start a pull request:
  1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
  2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by blake-mealey** [comment]
Hi, thanks for doing this first-timers thing! I'd like to tackle this one. Just to clarify, from looking at that readme, it already has a link to the license, however it goes to an offsite page rather than a direct link to the license file. Is that what you wanted changed?

**Comment by leighphan** [comment]
:wave: Hi Blake, sorry for the confusion - this issue is actually reserved for a Hacktoberfest event today (please see banner at top). If this issue is still open tomorrow, feel free to take a look! 

Any open issues will be freed up tonight and we'll also create new issues in the near future!

**Comment by jtru71** [comment]
I would like to claim this issue.

**Comment by gr2m** [comment]
@jtru71 are you working on this one? If yes, can you assign yourself and check of the steps above that you’ve already done? :)

**Comment by ryzokuken** [comment]
They claimed this 3 days ago, but didn't assign themselves. If everyone's okay with this, I'd like to claim this issue as my very first.

**Comment by MarckK** [comment]
I'd like to claim this!

**Comment by g-akash** [comment]
I would like to claim this.

**Comment by MarckK** [comment]
Hi,
I'm sorry to have to ask, but I can't see how to assign myself to this
issue, nor how to change the label to in progress!

Kind regards,
Kara

**Comment by gr2m** [comment]
@MarckK we will choose a person by random tomorrow to work on it :) Did you contribute to an open source project before?

**Comment by MarckK** [comment]
Hi,

No.  So, if not this particular issue, could I be assigned at least one
issue?

Kind regards,
Kara

**Comment by gr2m** [comment]
we will assign someone by random tomorrow :) We only have that many issues available, I’m afraid. This is an independent community project, we all do this in our free time, so please be patient with us :)

**Comment by 7ictor** [comment]
I want to work on this!, tried #80 with no luck, I have hope this time 💪

**Comment by Stefan-Mitic** [comment]
I would like to claim this issue.

**Comment by gr2m** [comment]
Hey @7ictor it’s your lucky day :) I’ve invited you to the repository: https://github.com/hoodiehq/camp/invitations Once accepted you can assign yourself and then work off the checklist above. Enjoy :) 

Sorry to the others, hope you find something else to work on! There are some good resources on http://www.firsttimersonly.com/
