### ISSUE TITLE
Correct link of code coverage badge in pouchdb-hoodie-sync’s README

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#87]
[![This issue is reserved for Write/Speak/Code Open Source Hours](https://dl.dropboxusercontent.com/u/732913/writespeakcode-opensourcehours.jpg)](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/?123)

### ☝ This issue is reserved for attendees of [Write/Speak/Code Open Source Hours](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/)

---

### 🤔 What you will need to know

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process

### ❓ The Motivation

This is `pouchdb-hoodie-sync`’s code coverage badge: [![Coverage Status](https://coveralls.io/repos/hoodiehq/pouchdb-hoodie-sync/badge.svg?branch=master)](https://coveralls.io/r/hoodiehq/hoodie?branch=master). You can see it on top of [`pouchdb-hoodie-sync`’s README](https://github.com/hoodiehq/pouchdb-hoodie-sync#readme).

The badge is linked to the [coverage detail page](https://coveralls.io/github/hoodiehq/pouchdb-hoodie-sync?branch=master). The URL of this page recently changed. The old URL is `https://coveralls.io/r/hoodiehq/pouchdb-hoodie-sync?branch=master` while the new one is `https://coveralls.io/github/hoodiehq/pouchdb-hoodie-sync?branch=master`. The user is currently redirected but we don’t know for how long, so better to update it to the new URL.

### :clipboard: Step by Step

- [ ] 🙋 **Claim this issue**: Comment below
  Please only claim if you want to start working on it during [the event](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/).
  Once claimed we add you as contributor to this repository.
- [ ] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this issue
- [ ] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind
- [ ] 🔄 **replace** the `up for grabs` label with `in progress`.
- [ ] 📝 **Update** [hoodiehq/pouchdb-hoodie-sync’s README.md file](https://github.com/hoodiehq/pouchdb-hoodie-sync/blob/master/README.md): Find the URL behind the code coverage badge (`https://coveralls.io/r/hoodiehq/pouchdb-hoodie-sync?branch=master`) and replace it with the new URL (`https://coveralls.io/github/hoodiehq/pouchdb-hoodie-sync?branch=master`)
- [ ] 💾 **Commit** your changes with the message `docs(README): new code coverage status URL`
- [ ] 🔀 **Start a Pull Request**. Set the title to `new code coverage status URL` and set description to `closes hoodiehq/camp#87`. There are two ways how you can start a pull request:
  1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
  2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [ ] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

### 🤔❓ Questions

Best is to ask @polinadotio who is at the event herself. You can also ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by yfalcon8** [comment]
I would like to claim this issue!

**Comment by rshen91** [comment]
Me too - thanks!
