### ISSUE TITLE
hoodie.account.isSignedIn() returns true in “signout" event handler

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/camp#9]
This is a [starter issue](http://hood.ie/blog/starter-issues.html).
### 🤔 What you will need to know

JavaScript, Node.js. Although this is code that runs in the browser, it looks like Node.js code and can be tested with node only.
### 🐞 The Bug

``` js
hoodie.account.on('signout', function () {
  alert(hoodie.account.isSignedIn()) // true, should be false
})
hoodie.account.signOut()
```

You can run the code on https://tracker.hood.ie/ – create an account, then open the console, paste it in and run it.
### :dart: The goal

`hoodie.account.isSignedIn()` should return false in the `'signout'` event handler.
### :clipboard: Step by Step
- [x] **claim this issue**: @dsims00
- [x] **mentor**: @gr2m
- [x] **[Setup the hoodie repository locally](https://github.com/hoodiehq/hoodie-account-client#testing)** and make sure that all tests pass
- [x] **Un-skip the test**: We prepared a test, follow the instructions [here](https://github.com/hoodiehq/hoodie-account-client/blob/master/test/integration/sign-out-test.js#L9-L14)
- [x] **Start a Pull Request**. Mention `closes hoodiehq/camp#9` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [ ] **Implement the fix** :) Make sure that tests pass again
- [ ] **Commit** with `fix: isSignedIn() returns false in signout event handler
- [ ] **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by dsims00** [comment]
I'd like to do this one

**Comment by gr2m** [comment]
@dsims00 all yours :) Check off the checkboxes above as you go :)

**Comment by dsims00** [comment]
@gr2m this will be my second PR!
