### ISSUE TITLE
Correct link of code coverage badge in hoodie-server’s README

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#95]
### 🆕🐥☝ First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 [About First Timers Only](http://www.firsttimersonly.com/).

### 🤔 What you will need to know

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process

### ❓ The Motivation

This is `hoodie-server`’s code coverage badge: [![Coverage Status](https://coveralls.io/repos/hoodiehq/hoodie-server/badge.svg?branch=master)](https://coveralls.io/r/hoodiehq/hoodie?branch=master). You can see it on top of [`hoodie-server`’s README](https://github.com/hoodiehq/hoodie-server#readme).

The badge is linked to the [coverage detail page](https://coveralls.io/github/hoodiehq/hoodie-server?branch=master). The URL of this page recently changed. The old URL is `https://coveralls.io/r/hoodiehq/hoodie-server?branch=master` while the new one is `https://coveralls.io/github/hoodiehq/hoodie-server?branch=master`. The user is currently redirected but we don’t know for how long, so better to update it to the new URL.

### :clipboard: Step by Step

- [x] 🙋 **Claim this issue**: Comment below
  Please only claim if you want to start working on it during [the event](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/).
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [ ] 📝 **Update** [hoodiehq/hoodie-server’s README.md file](https://github.com/hoodiehq/hoodie-server/blob/master/README.md): Find the URL behind the code coverage badge (`https://coveralls.io/r/hoodiehq/hoodie-server?branch=master`) and replace it with the new URL (`https://coveralls.io/github/hoodiehq/hoodie-server?branch=master`)
- [ ] 💾 **Commit** your changes with the message `docs(README): new code coverage status URL`
- [ ] 🔀 **Start a Pull Request**. Set the title to `new code coverage status URL` and set description to `closes hoodiehq/camp#123. There are two ways how you can start a pull request:
  1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
  2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [ ] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

### 🤔❓ Questions

Best is to ask @polinadotio who is at the event herself. You can also ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by nickdex** [comment]
Hello @LowProfileDog , I'm adding an issue for first-timers as well and I was wondering if you could provide the template for the issue above if not too much of a trouble.
Thanks :smile:

**Comment by LowProfileDog** [comment]
Not at all: our template is here: https://github.com/hoodiehq/camp/blob/gh-pages/ISSUE_TEMPLATE.md – hope that helps :) Here are some thoughts behind these issues: http://hood.ie/blog/starter-issues.html

**Comment by nickdex** [comment]
Wow I didn't expect a full blown tutorial for creating starter issues. I would like to thank you on behalf all the people that I'm going to refer haha. 
I'm a newbie to open source myself and I really appreciate the work that you are doing.

**Comment by LowProfileDog** [comment]
![giphy](https://cloud.githubusercontent.com/assets/17463029/21472360/610d417c-ca8a-11e6-9002-be31013159ec.gif)

_wiggle waggle_

**Comment by nickdex** [comment]
Haha that's cute :smile:

**Comment by varjmes** [comment]
@simonehaas are you still working on this? :)

**Comment by italo-batista** [comment]
hi! is this issue still open? :}

**Comment by ghost** [comment]
Is anybody working on this? 
I can pick this issue. :)

**Comment by gr2m** [comment]
@AkshayGulhane I’m afraid yes, Simone and I will finish that issue this week

**Comment by ghost** [comment]
@gr2m Sounds good! :) 👍

**Comment by gautamkrishnar** [comment]
@aksh77 i think this one is good for you. Please comment here if you want to work on this...

**Comment by gr2m** [comment]
it’s taken I’m sorry :)

**Comment by gautamkrishnar** [comment]
Okay @gr2m next time...
