### ISSUE TITLE
Correct link of code coverage badge in hoodie-account-server-api’s README

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#97]
### 🆕🐥☝ First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 [About First Timers Only](http://www.firsttimersonly.com/).

### 🤔 What you will need to know

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process

### ❓ The Motivation

This is `hoodie-account-server-api`’s code coverage badge: [![Coverage Status](https://coveralls.io/repos/hoodiehq/hoodie-account-server-api/badge.svg?branch=master)](https://coveralls.io/r/hoodiehq/hoodie?branch=master). You can see it on top of [`hoodie-account-server-api`’s README](https://github.com/hoodiehq/hoodie-account-server-api#readme).

The badge is linked to the [coverage detail page](https://coveralls.io/github/hoodiehq/hoodie-account-server-api?branch=master). The URL of this page recently changed. The old URL is `https://coveralls.io/r/hoodiehq/hoodie-account-server-api?branch=master` while the new one is `https://coveralls.io/github/hoodiehq/hoodie-account-server-api?branch=master`. The user is currently redirected but we don’t know for how long, so better to update it to the new URL.

### :clipboard: Step by Step

- [x] 🙋 **Claim this issue**: Comment below
  Please only claim if you want to start working on it during [the event](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/).
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 📝 **Update** [hoodiehq/hoodie-account-server-api’s README.md file](https://github.com/hoodiehq/hoodie-account-server-api/blob/master/README.md): Find the URL behind the code coverage badge (`https://coveralls.io/r/hoodiehq/hoodie-account-server-api?branch=master`) and replace it with the new URL (`https://coveralls.io/github/hoodiehq/hoodie-account-server-api?branch=master`)
- [x] 💾 **Commit** your changes with the message `docs(README): new code coverage status URL`
- [x] 🔀 **Start a Pull Request**. Set the title to `new code coverage status URL` and set description to `closes hoodiehq/camp#123. There are two ways how you can start a pull request:
  1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
  2. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

### 🤔❓ Questions

Best is to ask @polinadotio who is at the event herself. You can also ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by shaduk** [comment]
Hi. This would be my first PR. Please allow me to collaborate on this issue. Thanks for making open source easy for first timers. :)

**Comment by LowProfileDog** [comment]
welcome @shaduk 👋 

The issue is all yours :) I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

**Comment by shaduk** [comment]
Hello @LowProfileDog Please review the changes I have done. Is there anything else I need to do?. Thanks for your support.

**Comment by gr2m** [comment]
it’s not yet done :) This issue gets closed once we merge your pull request, I’ll have a look now
