### ISSUE TITLE
Merge @hoodie/store & @hoodie/account into hoodie

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#98]
### 🤔 What you will need to know

You will need to know Node.js and npm and have an understanding how modular Node.js projects work. You should have written tests before, ideally acceptance tests. At Hoodie, we use [tap](http://node-tap.org) as our test runner and will start using [selsa](https://github.com/gr2m/selsa) to handle Selenium, Sauce Labs and Webdriver.

### ❓ The Background

While working on the new Hoodie Architecture, we created the [`@hoodie/store`](https://github.com/hoodiehq/hoodie-store#readme) and [`@hoodie/account`](https://github.com/hoodiehq/hoodie-account#readme) modules as a way to combine the client & server logic of the store & account core modules, mostly for testing before the whole architecture was ready.

The idea was to make an architecture like this:

```
hoodie
├─┬ @hoodie/account
│ ├── @hoodie/account-client
│ └── @hoodie/account-server
└─┬ @hoodie/store
  ├── @hoodie/store-client
  └── @hoodie/store-server
```

But instead it turned out to more like

```
hoodie
├─┬ @hoodie/client
│ ├── @hoodie/account-client
│ └── @hoodie/store-client
└─┬ @hoodie/server
  ├── @hoodie/account-server
  └── @hoodie/store-server
```

`hoodie` still has [`@hoodie/account` and `@hoodie/store` in its dependencies](https://github.com/hoodiehq/hoodie/blob/45baeaf4023516154ea6b63e83774a77af1c5fc4/package.json#L14-L18). But the only thing we use it for now is to display the custom UI at `/hoodie/store` ([source](https://github.com/hoodiehq/hoodie-store/tree/master/public)) and `/hoodie/account` ([source](https://github.com/hoodiehq/hoodie-account/tree/master/public)), so just static assets.

We also use it for [account server/client acceptance tests](https://github.com/hoodiehq/hoodie-account/blob/master/test/integration.js) and  [store server/client acceptance tests](https://github.com/hoodiehq/hoodie-store/blob/master/test/integration.js). Note that these are implemented usin [frontend-test-setup](https://github.com/gr2m/frontend-test-setup), but we want to use [selsa](https://travis-ci.org/gr2m/selsa) now, as it is more robust, flexible and easier to debug.

### 🙌 The Motivation

This will simplify our architecture, reduce maintenance and it’s fairly simply todo without breaking changes.

For one, there is no use for the `@hoodie/account` or `@hoodie/store` modules outside Hoodie. And even if there were, it would be simple to create. `@hoodie/client` and `@hoodie/server` on the other side are used as direct dependencies in related projects.

Second, we want to have a custom hoodie UI that every hoodie app gets by default (related: https://github.com/hoodiehq/camp/issues/20, https://github.com/hoodiehq/camp/issues/21, https://github.com/hoodiehq/camp/issues/22). The UI is interdependent though, having the store page come from the store module and the account page from the account module makes little sense. So just having one integrated UI that simply lives at `/hoodie` is much simpler to create and to maintain. And we can use for integration tests of all the core features without needing an app.

### :clipboard: Step by Step

- [x] 🙋 **Claim this issue**: Comment below
  Please only claim if you want to start working on it during [the event](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/).
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this issue
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)
  In a nutshell: be patient and actively kind
- [x] 🔄 **replace** add the `in progress` label.
- [x] Fork the [hoodiehq/hoodie](https://github.com/hoodiehq/hoodie)
- [x] [Set it up locally](https://github.com/hoodiehq/hoodie#testing) by cloning your fork. Make sure that all tests pass
- [x] Move the contents of the `public` servers of [hoodie-store](https://github.com/hoodiehq/hoodie-store) and [hoodie-account](https://github.com/hoodiehq/hoodie-account) into [hoodie](https://github.com/hoodiehq/hoodie)’s `/public/store` and `/public/account` folders respectively. You can verify if it worked by running `npm start` and then open http://localhost:8080/store/ and http://localhost:8080/account/
- [x] 🔀 **Start a Pull Request**. Set the title to `Merge @hoodie/store & @hoodie/account into hoodie` and set description to `closes hoodiehq/camp#{THIS ISSUE NUMBER}`. If you never started a pull request on GitHub, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to do that. 
- [x] Next up: the tests. Create a new folder `test/acceptance` and a new file `test/acceptance/index.js`. Create the most simple test possible using `tap` (compare the other test files) and [selsa](https://github.com/gr2m/selsa). For example, open 
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

### 🤔❓ Questions

Best is to ask @polinadotio who is at the event herself. You can also ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by gr2m** [comment]
I’ll look into it :)

**Comment by gr2m** [comment]
The PR is ready for review https://github.com/hoodiehq/hoodie/issues/666 👓 👀
