### ISSUE TITLE
hood.ie/chat: fix the page title

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#99]
[![This issue is reserved for Write/Speak/Code Open Source Hours](https://dl.dropboxusercontent.com/u/732913/writespeakcode-opensourcehours.jpg)](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/?123)

### ☝ This issue is reserved for attendees of [Write/Speak/Code Open Source Hours](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/)

---

### 🤔 What you will need to know

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you trough the process

### ❓ The Motivation

Back in the days before Slack, the only way to chat with us was by using IRC. If you don’t know what that is, don’t worry :) Today, you can join our slack group at http://hood.ie/chat/. But the title of the page still says `hood.ie IRC`. It’s about time we change that to `hood.ie chat`

### :clipboard: Step by Step

- [ ] 🙋 **Claim this issue**: Comment below
  Please only claim if you want to start working on it during [the event](https://www.meetup.com/WriteSpeakCode-SFBay/events/235091424/).
  Once claimed we add you as contributor to this repository.
- [ ] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this issue
- [ ] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind
- [ ] 🔄 **replace** the `up for grabs` label with `in progress`.
- [ ] 📝 **Update** [chat/index.html file in the hood.ie repository](https://github.com/hoodiehq/hood.ie/blob/gh-pages/chat/index.html). Find and replace `hood.ie IRC` with `hood.ie chat`. You can edit the file right on github.com, here are [some instructions](https://help.github.com/articles/editing-files-in-your-repository/) :)
- [ ] 💾 **Commit** your changes with the message `new chat page title`
- [ ] 🔀 **Start a Pull Request**. Set the title to `new chat page title` and set description to `closes hoodiehq/camp#99`
- [ ] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

### 🤔❓ Questions

Best is to ask @polinadotio who is at the event herself. You can also ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by jeanhl** [comment]
Claimed!   :)

**Comment by jeanhl** [comment]
Please review! 💃 💃 💃

**Comment by gr2m** [comment]
Hey Jean, I just saw your comment in https://github.com/hoodiehq/camp/issues/105. I plan to create a few more camp issues over the weekend, I’ll ping you when I find one for you :)

**Comment by jeanhl** [comment]
Yay!

I look forward to it, Gregor.

**Comment by gr2m** [comment]
are you on twitter by chance?

**Comment by jeanhl** [comment]
Hey Gregor, 

Sorry for the late reply. It's been a busy weekend (I'm job searching). My twitter handle is @JiinLiu . I use it for primarily for content consumption, it looks a little neglected. 

:

**Comment by gr2m** [comment]
happy to help with the outreach :) Do you have anything online that we can share? Anything particular you are looking for?
